"""
Product Catalog Dataset Part 4: Gaming & Accessories + Personal Care + Books & Stationery.
Authentic Indian Rupee (INR) pricing, specs, multi-vendor seller assignments.
"""

PRODUCTS_LIFESTYLE = [
    # =========================================================================
    # 7. GAMING & ACCESSORIES (22 Products)
    # =========================================================================
    {
        "sku": "GAM-SNY-PS5-SLIM-DISC",
        "name": "Sony PlayStation 5 Console Slim Edition (1TB SSD, DualSense Controller)",
        "slug": "sony-playstation-5-slim-console",
        "category": "gaming-accessories",
        "brand": "sony",
        "seller": "apexcomputex",
        "price": 54990.0, "compare": 54990.0, "stock": 25, "rating": 4.9, "reviews": 120, "sales": 410, "featured": True,
        "desc": "Next-gen gaming redefined with ultra-high speed 1TB SSD, haptic feedback and adaptive triggers on DualSense wireless controller, 3D Audio, and 4K-120Hz ray tracing.",
        "attr": {"storage": "1TB Custom NVMe SSD", "resolution": "Up to 4K 120Hz / 8K Output", "audio": "Tempest 3D AudioTech", "controller": "DualSense Wireless Controller Included"},
        "images": ["https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-SNY-DUALSENSE-WHT",
        "name": "Sony DualSense Wireless Controller for PlayStation 5 (White)",
        "slug": "sony-dualsense-controller-white",
        "category": "gaming-accessories",
        "brand": "sony",
        "seller": "apexcomputex",
        "price": 5990.0, "compare": 6390.0, "stock": 90, "rating": 4.8, "reviews": 160, "sales": 680, "featured": False,
        "desc": "Immersive haptic feedback, dynamic adaptive triggers, built-in microphone and headset jack, all integrated into an iconic comfortable design.",
        "attr": {"connectivity": "Bluetooth 5.1 / USB Type-C", "features": "Haptic Feedback, Adaptive Triggers, Motion Sensor"},
        "images": ["https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-LOGI-G-PRO-X-SUPERLIGHT",
        "name": "Logitech G PRO X SUPERLIGHT 2 Lightspeed Wireless Gaming Mouse (White)",
        "slug": "logitech-g-pro-x-superlight-2",
        "category": "gaming-accessories",
        "brand": "logitech",
        "seller": "apexcomputex",
        "price": 14995.0, "compare": 16995.0, "stock": 45, "rating": 4.9, "reviews": 88, "sales": 290, "featured": True,
        "desc": "Weighing only 60 grams, the championship esports choice. Features HERO 2 sensor with 32,000 DPI, LIGHTFORCE hybrid optical-mechanical switches, and 95 hours battery life.",
        "attr": {"weight": "60 grams Ultra-Lightweight", "sensor": "HERO 2 32,000 DPI", "switches": "LIGHTFORCE Hybrid Optical-Mechanical"},
        "images": ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-LOGI-G915-TKL-RGB",
        "name": "Logitech G915 LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard (GL Tactile)",
        "slug": "logitech-g915-lightspeed-wireless-keyboard",
        "category": "gaming-accessories",
        "brand": "logitech",
        "seller": "apexcomputex",
        "price": 18995.0, "compare": 22995.0, "stock": 35, "rating": 4.8, "reviews": 65, "sales": 210, "featured": False,
        "desc": "Pro-grade LIGHTSPEED wireless, advanced LIGHTSYNC RGB, high-performance low-profile mechanical switches, crafted from aircraft-grade 5052 aluminum alloy.",
        "attr": {"switches": "GL Tactile Low-Profile", "battery": "40 Hours Non-Stop with RGB On", "connectivity": "LIGHTSPEED Wireless / Bluetooth"},
        "images": ["https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-LOGI-G733-HEADSET",
        "name": "Logitech G733 LIGHTSPEED Wireless RGB Gaming Headset with Blue VO!CE (Black)",
        "slug": "logitech-g733-lightspeed-headset-black",
        "category": "gaming-accessories",
        "brand": "logitech",
        "seller": "apexcomputex",
        "price": 11995.0, "compare": 14995.0, "stock": 55, "rating": 4.7, "reviews": 75, "sales": 250, "featured": False,
        "desc": "Ultra-lightweight 278g wireless headset with 29 hours of battery life, PRO-G 40mm audio drivers, DTS Headphone:X 2.0 surround sound, and reversible suspension headband.",
        "attr": {"drivers": "PRO-G 40mm", "surround": "DTS Headphone:X 2.0", "weight": "278 grams", "mic": "Detachable with Blue VO!CE filters"},
        "images": ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-ASU-ROG-SWIFT-32",
        "name": "ASUS ROG Swift OLED PG32UCDM 32-inch 4K 240Hz QD-OLED Gaming Monitor",
        "slug": "asus-rog-swift-oled-32-4k-240hz",
        "category": "gaming-accessories",
        "brand": "asus",
        "seller": "apexcomputex",
        "price": 139990.0, "compare": 159990.0, "stock": 10, "rating": 4.9, "reviews": 24, "sales": 50, "featured": True,
        "desc": "The ultimate gaming display: 32-inch 4K QD-OLED panel with blazing 240Hz refresh rate, 0.03ms response time, custom heatsink with graphene film, and Type-C 90W.",
        "attr": {"panel": "32-inch 4K QD-OLED", "refresh_rate": "240Hz", "response_time": "0.03ms", "hdr": "DisplayHDR True Black 400"},
        "images": ["https://images.unsplash.com/photo-1547119957-637f8679db1e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-LOGI-G29-RACING",
        "name": "Logitech G29 Driving Force Racing Wheel & Floor Pedals for PS5/PC",
        "slug": "logitech-g29-racing-wheel-pedals",
        "category": "gaming-accessories",
        "brand": "logitech",
        "seller": "apexcomputex",
        "price": 28995.0, "compare": 36995.0, "stock": 20, "rating": 4.8, "reviews": 90, "sales": 230, "featured": False,
        "desc": "Realistic dual-motor force feedback simulates the feel of tires on every turn, hand-stitched leather wheel cover, 900-degree rotation, responsive stainless pedals.",
        "attr": {"rotation": "900-Degree Lock-to-Lock", "feedback": "Dual-Motor Force Feedback", "pedals": "Nonlinear Stainless Steel Pedals"},
        "images": ["https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-ASU-ROG-FALCHION-RX",
        "name": "ASUS ROG Falchion RX Low-Profile 65% Wireless Gaming Keyboard (Red Switches)",
        "slug": "asus-rog-falchion-rx-wireless-keyboard",
        "category": "gaming-accessories",
        "brand": "asus",
        "seller": "apexcomputex",
        "price": 14999.0, "compare": 17999.0, "stock": 30, "rating": 4.8, "reviews": 40, "sales": 130, "featured": False,
        "desc": "Compact 65% form factor in a 60% frame with pre-lubed ROG RX Low-Profile optical switches, interactive touch panel on the left edge, and tri-mode connectivity.",
        "attr": {"form_factor": "65% Compact", "switches": "ROG RX Red Optical", "connectivity": "Tri-Mode (2.4GHz / BT / USB-C)"},
        "images": ["https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-LOGI-G435-LIGHTSPEED",
        "name": "Logitech G435 Ultra-Lightweight Wireless Gaming Headset (Blue & Raspberry)",
        "slug": "logitech-g435-lightspeed-blue",
        "category": "gaming-accessories",
        "brand": "logitech",
        "seller": "soundwave",
        "price": 4995.0, "compare": 6995.0, "stock": 95, "rating": 4.6, "reviews": 140, "sales": 510, "featured": False,
        "desc": "Weighs only 165 grams with dual beamforming microphones that reduce background noise without a boom arm. Certified CarbonNeutral and Dolby Atmos compatible.",
        "attr": {"weight": "165 grams Ultra-Light", "battery": "18 Hours Playtime", "connectivity": "LIGHTSPEED Wireless + Bluetooth"},
        "images": ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-SAN-EXTREME-PRO-MICROSD",
        "name": "SanDisk Extreme PRO 256GB microSDXC UHS-I Card for Nintendo Switch & Steam Deck",
        "slug": "sandisk-extreme-pro-256gb-microsd",
        "category": "gaming-accessories",
        "brand": "sandisk",
        "seller": "digitalhub",
        "price": 2799.0, "compare": 4999.0, "stock": 190, "rating": 4.9, "reviews": 260, "sales": 1150, "featured": False,
        "desc": "Speed class A2 for fast handheld game loading with up to 200MB/s read and 140MB/s write speeds, temperature-proof, waterproof, and x-ray proof.",
        "attr": {"capacity": "256GB", "read_speed": "Up to 200MB/s", "app_performance": "A2 Rating for High-Speed Gaming"},
        "images": ["https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-ACR-NITRO-VG270",
        "name": "Acer Nitro VG270 27-inch Full HD 165Hz IPS Gaming Monitor (0.5ms, HDR10)",
        "slug": "acer-nitro-vg270-165hz-monitor",
        "category": "gaming-accessories",
        "brand": "acer",
        "seller": "apexcomputex",
        "price": 11499.0, "compare": 16999.0, "stock": 70, "rating": 4.6, "reviews": 195, "sales": 720, "featured": False,
        "desc": "ZeroFrame design with 165Hz overclocked refresh rate, 0.5ms minimum response time, AMD FreeSync Premium, stereo 2W integrated speakers, and HDR10 support.",
        "attr": {"size": "27 inch", "resolution": "Full HD (1920x1080)", "refresh": "165Hz Overclocked", "sync": "AMD FreeSync Premium"},
        "images": ["https://images.unsplash.com/photo-1547119957-637f8679db1e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-ASU-ROG-CHAKRAM-X",
        "name": "ASUS ROG Chakram X Origin Wireless Ergonomic Gaming Mouse with Joystick",
        "slug": "asus-rog-chakram-x-gaming-mouse",
        "category": "gaming-accessories",
        "brand": "asus",
        "seller": "apexcomputex",
        "price": 12999.0, "compare": 15999.0, "stock": 25, "rating": 4.7, "reviews": 32, "sales": 85, "featured": False,
        "desc": "Equipped with 36,000 DPI ROG AimPoint optical sensor, 8000Hz polling rate, integrated programmable analog/digital thumb joystick, and push-fit switch sockets.",
        "attr": {"sensor": "36,000 DPI ROG AimPoint", "joystick": "Built-in Thumb Joystick (Analog/Digital)", "battery": "114 Hours Max"},
        "images": ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-LOGI-G213-PRODIGY",
        "name": "Logitech G213 Prodigy Spill-Resistant RGB Gaming Keyboard with Mech-Dome Keys",
        "slug": "logitech-g213-prodigy-rgb-keyboard",
        "category": "gaming-accessories",
        "brand": "logitech",
        "seller": "smartbuystore",
        "price": 3795.0, "compare": 4995.0, "stock": 110, "rating": 4.5, "reviews": 230, "sales": 840, "featured": False,
        "desc": "Tuned Mech-Dome keys deliver tactile response comparable to mechanical boards with 4x faster response than standard keyboards. 60ml spill resistance tested.",
        "attr": {"keys": "Mech-Dome Tactile Keys", "rgb": "5-Zone LIGHTSYNC RGB", "spill_resistant": "60ml Tested Durability"},
        "images": ["https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-SNY-INZONE-H9",
        "name": "Sony INZONE H9 Wireless Noise Canceling Spatial Gaming Headset (White)",
        "slug": "sony-inzone-h9-wireless-headset",
        "category": "gaming-accessories",
        "brand": "sony",
        "seller": "audioplanet",
        "price": 21990.0, "compare": 27990.0, "stock": 30, "rating": 4.8, "reviews": 45, "sales": 140, "featured": False,
        "desc": "360 Spatial Sound for Gaming identifies pinpoint enemy footsteps. Dual Sensor Noise Cancelling technology blocks out background household racket.",
        "attr": {"anc": "Dual Sensor Active Noise Cancelling", "sound": "360 Spatial Sound for Gaming", "battery": "32 Hours with Quick Charge"},
        "images": ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-LOGI-G440-HARD-PAD",
        "name": "Logitech G440 Hard Polymer Low Friction Gaming Mouse Pad (Black)",
        "slug": "logitech-g440-hard-gaming-mouse-pad",
        "category": "gaming-accessories",
        "brand": "logitech",
        "seller": "apexcomputex",
        "price": 1995.0, "compare": 2495.0, "stock": 140, "rating": 4.6, "reviews": 160, "sales": 610, "featured": False,
        "desc": "Ultra-low surface friction polyethylene hard top allows rapid high-DPI mouse flicks with minimal muscle effort. Natural rubber base grips desktop firmly.",
        "attr": {"surface": "Hard Polyethylene Low-Friction", "dimensions": "340 x 280 x 3 mm", "base": "Natural Non-Slip Rubber Base"},
        "images": ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-ACR-PRED-CESTUS-335",
        "name": "Acer Predator Cestus 335 Ergonomic Gaming Mouse with Hyper-Fast Scroll",
        "slug": "acer-predator-cestus-335-mouse",
        "category": "gaming-accessories",
        "brand": "acer",
        "seller": "smartbuystore",
        "price": 2999.0, "compare": 4499.0, "stock": 90, "rating": 4.5, "reviews": 75, "sales": 290, "featured": False,
        "desc": "PixArt 3370 sensor with up to 19,000 DPI, 10 programmable buttons with 5-profile onboard memory, and hyper-fast dual-mode free spin scroll wheel.",
        "attr": {"sensor": "PixArt 3370 (19,000 DPI)", "buttons": "10 Programmable", "scroll": "Hyper-Fast Free Spin Wheel"},
        "images": ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-ASU-TUF-GAMING-K1",
        "name": "ASUS TUF Gaming K1 RGB Keyboard with Dedicated Volume Knob (Spill-Resistant)",
        "slug": "asus-tuf-gaming-k1-keyboard",
        "category": "gaming-accessories",
        "brand": "asus",
        "seller": "smartbuystore",
        "price": 2899.0, "compare": 3999.0, "stock": 115, "rating": 4.5, "reviews": 110, "sales": 450, "featured": False,
        "desc": "Tactile TUF Gaming switches with 19-key rollover, dedicated rotary audio volume knob at upper right, dynamic RGB lighting side bars, and 300ml spill resistance.",
        "attr": {"volume_knob": "Dedicated Precision Dial", "spill_proof": "300ml Spill Resistance", "wrist_rest": "Detachable Ergonomic Rest"},
        "images": ["https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-SNY-PULSE-EXPLORE",
        "name": "Sony PULSE Explore Wireless Earbuds with Planar Magnetic Drivers (PS5/PC)",
        "slug": "sony-pulse-explore-wireless-earbuds",
        "category": "gaming-accessories",
        "brand": "sony",
        "seller": "audioplanet",
        "price": 18990.0, "compare": 21990.0, "stock": 35, "rating": 4.8, "reviews": 50, "sales": 160, "featured": False,
        "desc": "Studio-inspired planar magnetic drivers reproduce ultra-realistic game soundscapes with lightning-fast PlayStation Link wireless lossless audio and AI noise rejection.",
        "attr": {"drivers": "Planar Magnetic Studio Drivers", "link": "PlayStation Link Ultra-Low Latency Lossless", "mic": "AI-Enhanced Noise Rejection"},
        "images": ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-LOGI-G304-LIGHTSPEED",
        "name": "Logitech G304 Lightspeed Wireless Gaming Mouse with HERO Sensor (Black)",
        "slug": "logitech-g304-lightspeed-mouse-black",
        "category": "gaming-accessories",
        "brand": "logitech",
        "seller": "smartbuystore",
        "price": 2795.0, "compare": 3795.0, "stock": 180, "rating": 4.7, "reviews": 380, "sales": 1500, "featured": False,
        "desc": "HERO optical sensor with 12,000 DPI accuracy and 400 IPS speed. LIGHTSPEED wireless technology with 1ms report rate and 250 hours endurance on one AA battery.",
        "attr": {"sensor": "HERO 12,000 DPI", "latency": "1ms LIGHTSPEED Wireless", "battery": "250 Hours Continuous on 1x AA"},
        "images": ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-SAN-EXTREME-PRO-CFX",
        "name": "SanDisk Extreme PRO 128GB CFexpress Type B Card for High-Res Game Capture",
        "slug": "sandisk-extreme-pro-128gb-cfexpress",
        "category": "gaming-accessories",
        "brand": "sandisk",
        "seller": "digitalhub",
        "price": 9999.0, "compare": 14999.0, "stock": 40, "rating": 4.8, "reviews": 35, "sales": 110, "featured": False,
        "desc": "Ultra-fast read speeds up to 1700MB/s and write speeds up to 1200MB/s with low latency recording of RAW 4K game capture footage without dropped frames.",
        "attr": {"read": "1700MB/s", "write": "1200MB/s", "format": "CFexpress Type B"},
        "images": ["https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-ACR-PRED-RGB-MOUSEPAD",
        "name": "Acer Predator RGB Gaming Mouse Pad with 16.8M Color Backlit Edge (XL Size)",
        "slug": "acer-predator-rgb-mousepad-xl",
        "category": "gaming-accessories",
        "brand": "acer",
        "seller": "apexcomputex",
        "price": 1999.0, "compare": 3499.0, "stock": 100, "rating": 4.5, "reviews": 85, "sales": 340, "featured": False,
        "desc": "Micro-textured woven cloth surface optimized for both optical and laser mouse sensors. 6 dynamic lighting effects with touch control button.",
        "attr": {"size": "XL (800 x 300 x 4 mm)", "rgb": "Edge-Lit 16.8 Million Colors", "surface": "Speed & Control Hybrid Cloth"},
        "images": ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GAM-LOGI-STREAMCAM-1080P",
        "name": "Logitech StreamCam 1080p 60fps Webcam with USB-C for Gaming Twitch Streams",
        "slug": "logitech-streamcam-1080p-60fps",
        "category": "gaming-accessories",
        "brand": "logitech",
        "seller": "apexcomputex",
        "price": 11995.0, "compare": 15995.0, "stock": 35, "rating": 4.7, "reviews": 70, "sales": 180, "featured": False,
        "desc": "Full HD 1080p at 60 fps for smooth, precise video stream motion. AI facial tracking smart auto-focus and exposure, with vertical video portrait mode.",
        "attr": {"video": "1080p at 60fps", "lens": "Premium Glass Lens f/2.0", "connection": "Direct USB 3.1 Type-C"},
        "images": ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop"]
    },

    # =========================================================================
    # 8. PERSONAL CARE & GROOMING (20 Products)
    # =========================================================================
    {
        "sku": "GRO-DYS-SUPERSONIC-DRYER",
        "name": "Dyson Supersonic Hair Dryer with Intelligent Heat Control (Iron / Fuchsia)",
        "slug": "dyson-supersonic-hair-dryer",
        "category": "personal-care",
        "brand": "dyson",
        "seller": "eliteliving",
        "price": 34900.0, "compare": 39900.0, "stock": 25, "rating": 4.9, "reviews": 85, "sales": 240, "featured": True,
        "desc": "Engineered to protect hair from extreme heat damage with fast drying and controlled styling. Powered by the Dyson digital motor V9 spinning up to 110,000rpm.",
        "attr": {"motor": "Dyson V9 Digital Motor", "attachments": "5 Styling Magnetic Attachments", "heat_control": "Measures Air Temp 40x per Second"},
        "images": ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-PHI-TRIMMER-BT3231",
        "name": "Philips BT3231/15 Smart Beard Trimmer with PowerAdapt Sensor (Green)",
        "slug": "philips-bt3231-smart-beard-trimmer",
        "category": "personal-care",
        "brand": "philips",
        "seller": "eliteliving",
        "price": 1699.0, "compare": 2295.0, "stock": 190, "rating": 4.6, "reviews": 280, "sales": 1150, "featured": True,
        "desc": "PowerAdapt Sensor checks beard density 125 times per second and adapts motor to match for effortless trimming without pulling hair. 60 min cordless run.",
        "attr": {"run_time": "60 Minutes Cordless Use", "precision": "20 Lock-in Length Settings (0.5 - 10mm)", "blades": "Self-Sharpening Titanium Coated"},
        "images": ["https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-PHI-ONEBLADE-QP2824",
        "name": "Philips OneBlade QP2824 Hybrid Beard Trimmer and Shaver for Face & Body",
        "slug": "philips-oneblade-hybrid-trimmer",
        "category": "personal-care",
        "brand": "philips",
        "seller": "eliteliving",
        "price": 1999.0, "compare": 2795.0, "stock": 160, "rating": 4.7, "reviews": 210, "sales": 890, "featured": False,
        "desc": "Trim, edge, and shave any length of hair without cutting skin. Fast-moving dual-sided blade moves 12,000 times per minute with protective skin guard.",
        "attr": {"blade": "Dual-Sided 360 Blade", "use": "Wet and Dry Shave with Foam or Gel", "body_guard": "Click-On Skin Guard Included"},
        "images": ["https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-DYS-AIRWRAP-MULTI",
        "name": "Dyson Airwrap Multi-Styler Complete Long for Multiple Hair Types (Nickel / Copper)",
        "slug": "dyson-airwrap-multi-styler-complete",
        "category": "personal-care",
        "brand": "dyson",
        "seller": "eliteliving",
        "price": 49900.0, "compare": 54900.0, "stock": 15, "rating": 4.9, "reviews": 60, "sales": 130, "featured": True,
        "desc": "Harnesses the aerodynamic phenomenon called the Coanda effect to attract and wrap hair using only air, not extreme heat, for voluminous curls and smooth waves.",
        "attr": {"technology": "Coanda Aerodynamic Air Effect", "barrels": "30mm & 40mm Re-engineered Airwrap Barrels", "case": "Prussian Blue Storage Case"},
        "images": ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-HAV-GS6451-SHAVER",
        "name": "Havells GS6451 3-Head 3D Rotary Electric Shaver (IPX7 100% Washable)",
        "slug": "havells-gs6451-3d-rotary-shaver",
        "category": "personal-care",
        "brand": "havells",
        "seller": "eliteliving",
        "price": 2299.0, "compare": 3495.0, "stock": 110, "rating": 4.5, "reviews": 95, "sales": 390, "featured": False,
        "desc": "3D floating rotary heads adjust to every curve of the jawline and neck. Built-in pop-up trimmer for sideburns and mustache detailing. 90-min runtime.",
        "attr": {"heads": "3D Floating Dual-Track Cutters", "battery": "90 Minutes Cordless Runtime", "waterproof": "IPX7 100% Fully Washable Body"},
        "images": ["https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-PHI-SONICARE-3100",
        "name": "Philips Sonicare 3100 Series Electric Toothbrush with Pressure Sensor (Sugar Rose)",
        "slug": "philips-sonicare-3100-electric-toothbrush",
        "category": "personal-care",
        "brand": "philips",
        "seller": "eliteliving",
        "price": 2999.0, "compare": 4295.0, "stock": 130, "rating": 4.8, "reviews": 160, "sales": 640, "featured": False,
        "desc": "Removes up to 3x more plaque than a manual toothbrush. Advanced sonic technology pulses micro-bubbles between teeth with built-in pressure sensor to protect gums.",
        "attr": {"vibrations": "31,000 Brush Strokes per Minute", "sensor": "Built-in Pressure Protection Sensor", "timer": "SmarTimer & QuadPacer 2min"},
        "images": ["https://images.unsplash.com/photo-1559591937-e1032397e55a?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-HAV-HD3151-DRYER",
        "name": "Havells HD3151 1200W Foldable Compact Hair Dryer with Cool Shot Button",
        "slug": "havells-hd3151-foldable-hair-dryer",
        "category": "personal-care",
        "brand": "havells",
        "seller": "eliteliving",
        "price": 1099.0, "compare": 1595.0, "stock": 200, "rating": 4.5, "reviews": 180, "sales": 820, "featured": False,
        "desc": "Gently dries hair with optimal airflow. Foldable handle makes it ideal for travel bags, featuring 3 temperature settings (Hot, Warm, Cool shot) and honeycomb inlet.",
        "attr": {"power": "1200 Watts", "settings": "3 Temperature Settings + Cool Air Shot", "handle": "Foldable Space-Saving Handle"},
        "images": ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-PHI-STRAIGHTENER-BHS393",
        "name": "Philips BHS393/40 SilkProtect Ceramic Hair Straightener with Titanium Infusion",
        "slug": "philips-silkprotect-hair-straightener",
        "category": "personal-care",
        "brand": "philips",
        "seller": "eliteliving",
        "price": 1799.0, "compare": 2195.0, "stock": 140, "rating": 4.6, "reviews": 190, "sales": 740, "featured": False,
        "desc": "SilkProtect technology prevents hair overheating with even heat distribution across titanium-infused ceramic plates. 60-second fast heat-up time.",
        "attr": {"plates": "Titanium-Infused Ceramic Plates (20x90mm)", "temp": "2 Heat Settings (190°C & 210°C)", "swivel": "1.6m 360-Degree Swivel Cord"},
        "images": ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-HAV-MULTI-GROOM-KIT",
        "name": "Havells 4-in-1 Multi-Grooming Kit (Beard, Nose, Ear Trimmer & Body Groomer)",
        "slug": "havells-4in1-multi-grooming-kit",
        "category": "personal-care",
        "brand": "havells",
        "seller": "eliteliving",
        "price": 1899.0, "compare": 2895.0, "stock": 105, "rating": 4.5, "reviews": 120, "sales": 490, "featured": False,
        "desc": "All-in-one grooming solution for face, hair, and body. Includes U-shape blade, rotary nose/ear attachment, foil shaver, and precision detailing head.",
        "attr": {"attachments": "4 Interchangeable Heads", "blades": "Hypoallergenic Stainless Steel Blades", "charging": "USB Quick Charging"},
        "images": ["https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-DYS-AIRSTRAIT-COPPER",
        "name": "Dyson Airstrait Wet-to-Dry Hair Straightener with Directional Airflow",
        "slug": "dyson-airstrait-wet-to-dry-straightener",
        "category": "personal-care",
        "brand": "dyson",
        "seller": "eliteliving",
        "price": 45900.0, "compare": 49900.0, "stock": 12, "rating": 4.9, "reviews": 38, "sales": 95, "featured": True,
        "desc": "Straightens from wet to dry with air. No hot plates. No extreme heat damage. High-velocity downward airflow projects air at a 45° angle to create tension.",
        "attr": {"modes": "Wet to Dry & Dry Styling Modes", "display": "High-Definition LCD Screen", "safety": "Auto-Pause Function When Put Down"},
        "images": ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-PHI-BODYGROOM-BG1025",
        "name": "Philips Bodygroom Series 1000 Showerproof Body Hair Trimmer with Skin Protector",
        "slug": "philips-bodygroom-series-1000",
        "category": "personal-care",
        "brand": "philips",
        "seller": "eliteliving",
        "price": 1499.0, "compare": 1895.0, "stock": 160, "rating": 4.6, "reviews": 210, "sales": 870, "featured": False,
        "desc": "Uniquely guards sensitive skin while trimming as close as 0.5mm. Bi-directional trimmer cuts forwards and backwards to catch all hair orientations.",
        "attr": {"guard": "Skin Protection Guard for Sensitive Zones", "shower": "100% Waterproof for in-shower use", "power": "Cordless AA Battery Powered"},
        "images": ["https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-HAV-PEDICURE-CALLUS",
        "name": "Havells CR4001 Rechargeable Electric Callus Remover for Smooth Heels",
        "slug": "havells-electric-callus-remover",
        "category": "personal-care",
        "brand": "havells",
        "seller": "eliteliving",
        "price": 1299.0, "compare": 1995.0, "stock": 90, "rating": 4.4, "reviews": 75, "sales": 310, "featured": False,
        "desc": "Micro-mineral roller head spins 360 degrees to gently buff away dead, hard, dry skin from heels in seconds. Includes extra fine and coarse rollers.",
        "attr": {"rollers": "2 Mineral Roller Heads (Coarse & Fine)", "battery": "USB Rechargeable Lithium Battery", "safety": "Pressure Safety Lock"},
        "images": ["https://images.unsplash.com/photo-1559591937-e1032397e55a?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-PHI-NOSE-EAR-NT1605",
        "name": "Philips Nose and Ear Hair Trimmer Series 1000 with PrecisionTrim Technology",
        "slug": "philips-nose-ear-trimmer-nt1605",
        "category": "personal-care",
        "brand": "philips",
        "seller": "eliteliving",
        "price": 899.0, "compare": 1195.0, "stock": 210, "rating": 4.6, "reviews": 250, "sales": 1100, "featured": False,
        "desc": "Ultimate comfort guaranteed with Protective Guard System that shields skin from the dual-sided cutter to ensure zero pulling and zero cuts.",
        "attr": {"technology": "PrecisionTrim Dual-Sided Blades", "safety": "Protective Guard System", "cleaning": "Fully Washable Head"},
        "images": ["https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-HAV-NAIL-SHAPING-KIT",
        "name": "Havells NP2001 Electric Manicure & Pedicure Nail Shaper Device with 5 Heads",
        "slug": "havells-electric-nail-shaper-kit",
        "category": "personal-care",
        "brand": "havells",
        "seller": "eliteliving",
        "price": 999.0, "compare": 1595.0, "stock": 80, "rating": 4.3, "reviews": 60, "sales": 240, "featured": False,
        "desc": "Shape, buff, smooth, and polish fingernails and toenails at home with dual rotation speed modes and 5 precision abrasive attachments.",
        "attr": {"attachments": "5 Head Attachments (Buffing, Shaping, Polishing)", "speed": "2 Speed Bi-Directional Modes", "power": "Battery Operated"},
        "images": ["https://images.unsplash.com/photo-1559591937-e1032397e55a?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-PHI-COMPACT-DRYER-1000",
        "name": "Philips HP8100/46 SalonDry Compact 1000W Hair Dryer (Blue)",
        "slug": "philips-hp8100-compact-hair-dryer",
        "category": "personal-care",
        "brand": "philips",
        "seller": "eliteliving",
        "price": 899.0, "compare": 1095.0, "stock": 250, "rating": 4.5, "reviews": 320, "sales": 1400, "featured": False,
        "desc": "Carefully balanced 1000W airflow dries hair fast without heat stress. Narrow concentrator nozzle focuses warm air for sleek salon-style blowouts.",
        "attr": {"wattage": "1000 Watts Gentle Drying", "nozzle": "Concentrator Nozzle Included", "cord": "1.5m Cord with Storage Hook"},
        "images": ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-HAV-FACIAL-CLEANSER",
        "name": "Havells SC5070 Sonic Wave Deep Pore Cleansing Facial Brush (Silicone)",
        "slug": "havells-sonic-facial-cleansing-brush",
        "category": "personal-care",
        "brand": "havells",
        "seller": "eliteliving",
        "price": 1499.0, "compare": 2395.0, "stock": 85, "rating": 4.5, "reviews": 70, "sales": 280, "featured": False,
        "desc": "Ultra-hygienic soft silicone touchpoints channel 6,000 sonic vibrations per minute to unclog makeup residue, dead skin cells, and blackheads.",
        "attr": {"material": "Antibacterial Food-Grade Silicone", "speeds": "6 Intensity Vibration Speeds", "waterproof": "IPX7 Waterproof for Shower"},
        "images": ["https://images.unsplash.com/photo-1559591937-e1032397e55a?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-PHI-TITANIUM-TRIMMER-PRO",
        "name": "Philips Series 5000 Pro Beard Trimmer with Lift & Trim PRO System (BT5515)",
        "slug": "philips-series-5000-pro-beard-trimmer",
        "category": "personal-care",
        "brand": "philips",
        "seller": "eliteliving",
        "price": 3299.0, "compare": 4495.0, "stock": 70, "rating": 4.8, "reviews": 110, "sales": 410, "featured": False,
        "desc": "Lift & Trim PRO system guides low-lying hairs towards the double-sharpened blades for an even trim in one pass. 90 minutes runtime with 40 length settings.",
        "attr": {"lengths": "40 Precision Length Settings (0.2mm Precision)", "battery": "90 Minutes Li-ion Battery", "washable": "100% Waterproof"},
        "images": ["https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-HAV-HEATED-EYELASH",
        "name": "Havells Quick-Heat Ergonomic Heated Eyelash Curler with Silicone Pad",
        "slug": "havells-heated-eyelash-curler",
        "category": "personal-care",
        "brand": "havells",
        "seller": "eliteliving",
        "price": 799.0, "compare": 1295.0, "stock": 120, "rating": 4.2, "reviews": 50, "sales": 210, "featured": False,
        "desc": "Temperature-sensing silicone pad turns from red to clear in 15 seconds indicating it is ready to give natural long-lasting dramatic curls.",
        "attr": {"heating_time": "15 Seconds Fast Heating", "pad": "Temperature Sensitive Silicone", "safety": "Anti-Scald Protective Eyelid Guard"},
        "images": ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-PHI-KERASHINE-HEATED",
        "name": "Philips BHH880/10 Heated Straightening Brush with Keratin-Infused Bristles",
        "slug": "philips-heated-straightening-brush",
        "category": "personal-care",
        "brand": "philips",
        "seller": "eliteliving",
        "price": 2799.0, "compare": 3695.0, "stock": 95, "rating": 4.7, "reviews": 140, "sales": 560, "featured": False,
        "desc": "Naturally straight, shiny, frizz-free hair in just 5 minutes. Paddle-shaped brush with ThermoProtect technology and tourmaline ceramic coating.",
        "attr": {"bristles": "Triple Bristle Design Detangles & Straightens", "coating": "Tourmaline Keratin Infused", "temp": "2 Settings (170°C & 200°C)"},
        "images": ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "GRO-HAV-CR1001-SHAVER",
        "name": "Havells CR1001 Cordless Foil Shaver with Pop-Up Sideburn Trimmer (Black)",
        "slug": "havells-cr1001-cordless-foil-shaver",
        "category": "personal-care",
        "brand": "havells",
        "seller": "eliteliving",
        "price": 1499.0, "compare": 2195.0, "stock": 130, "rating": 4.4, "reviews": 85, "sales": 340, "featured": False,
        "desc": "Dual reciprocating floating foils lift and capture flat-lying stubble cleanly. Ultra-compact lightweight pocket design for on-the-go business travel.",
        "attr": {"foil": "Dual Reciprocating Titanium Foils", "runtime": "45 Minutes Continuous Operation", "extras": "Protective Travel Cap Included"},
        "images": ["https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&auto=format&fit=crop"]
    },

    # =========================================================================
    # 9. BOOKS & STATIONERY (18 Products)
    # =========================================================================
    {
        "sku": "BOK-PSYCHOLOGY-OF-MONEY",
        "name": "The Psychology of Money by Morgan Housel (Paperback Bestseller)",
        "slug": "the-psychology-of-money-morgan-housel",
        "category": "books-stationery",
        "brand": "penguin",
        "seller": "eliteliving",
        "price": 349.0, "compare": 499.0, "stock": 250, "rating": 4.9, "reviews": 420, "sales": 1800, "featured": True,
        "desc": "Timeless lessons on wealth, greed, and happiness. Doing well with money isn't necessarily about what you know. It's about how you behave.",
        "attr": {"author": "Morgan Housel", "pages": "256 Pages", "format": "Paperback", "language": "English"},
        "images": ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "BOK-ATOMIC-HABITS-CLEAR",
        "name": "Atomic Habits: An Easy & Proven Way to Build Good Habits by James Clear",
        "slug": "atomic-habits-james-clear",
        "category": "books-stationery",
        "brand": "penguin",
        "seller": "eliteliving",
        "price": 499.0, "compare": 799.0, "stock": 310, "rating": 4.9, "reviews": 510, "sales": 2200, "featured": True,
        "desc": "The #1 New York Times bestseller. Over 15 million copies sold. A revolutionary system to get 1% better every day through tiny behavioral shifts.",
        "attr": {"author": "James Clear", "pages": "320 Pages", "format": "Paperback", "genre": "Self-Improvement & Productivity"},
        "images": ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "BOK-DESIGNING-DATA-INTENSIVE",
        "name": "Designing Data-Intensive Applications by Martin Kleppmann (O'Reilly Technical)",
        "slug": "designing-data-intensive-applications-kleppmann",
        "category": "books-stationery",
        "brand": "oreilly",
        "seller": "digitalhub",
        "price": 1499.0, "compare": 1899.0, "stock": 80, "rating": 4.9, "reviews": 190, "sales": 640, "featured": True,
        "desc": "The definitive software engineering architecture bible. Explores principles, distributed consensus, data modeling, stream processing, and storage engines.",
        "attr": {"author": "Martin Kleppmann", "publisher": "O'Reilly Media", "pages": "616 Pages", "topic": "Distributed Systems & Databases"},
        "images": ["https://images.unsplash.com/photo-1532012164546-f432f2e3777a?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "BOK-CLEAN-CODE-MARTIN",
        "name": "Clean Code: A Handbook of Agile Software Craftsmanship by Robert C. Martin",
        "slug": "clean-code-robert-martin",
        "category": "books-stationery",
        "brand": "oreilly",
        "seller": "digitalhub",
        "price": 899.0, "compare": 1299.0, "stock": 110, "rating": 4.8, "reviews": 160, "sales": 580, "featured": False,
        "desc": "Even bad code can function. But if code isn't clean, it can bring a development organization to its knees. Master naming, functions, classes, and refactoring.",
        "attr": {"author": "Robert C. Martin (Uncle Bob)", "pages": "464 Pages", "publisher": "Prentice Hall", "topic": "Software Engineering"},
        "images": ["https://images.unsplash.com/photo-1532012164546-f432f2e3777a?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "BOK-DEEP-WORK-NEWPORT",
        "name": "Deep Work: Rules for Focused Success in a Distracted World by Cal Newport",
        "slug": "deep-work-cal-newport",
        "category": "books-stationery",
        "brand": "penguin",
        "seller": "eliteliving",
        "price": 399.0, "compare": 599.0, "stock": 180, "rating": 4.8, "reviews": 230, "sales": 910, "featured": False,
        "desc": "One of the most valuable skills in our economy is becoming increasingly rare. If you master this skill, you'll achieve extraordinary results.",
        "attr": {"author": "Cal Newport", "pages": "304 Pages", "format": "Paperback", "focus": "Focus & Career Mastery"},
        "images": ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "STA-MOLESKINE-CLASSIC-NB",
        "name": "Moleskine Classic Hardcover Ruled Large Notebook (Sapphire Blue, 240 Pages)",
        "slug": "moleskine-classic-notebook-sapphire-blue",
        "category": "books-stationery",
        "brand": "moleskine",
        "seller": "eliteliving",
        "price": 1999.0, "compare": 2499.0, "stock": 90, "rating": 4.8, "reviews": 130, "sales": 420, "featured": True,
        "desc": "The legendary notebook used by artists and thinkers. Acid-free 70 gsm ivory paper, rounded corners, ribbon bookmark, and expandable inner rear pocket.",
        "attr": {"size": "Large (13 x 21 cm)", "pages": "240 Ruled Pages (70 gsm)", "cover": "Hard Cover with Elastic Closure"},
        "images": ["https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "STA-PARKER-VECTOR-PEN",
        "name": "Parker Vector Metallic Matte Black CT Fountain Pen with Chrome Trim",
        "slug": "parker-vector-fountain-pen-black",
        "category": "books-stationery",
        "brand": "parker",
        "seller": "eliteliving",
        "price": 499.0, "compare": 750.0, "stock": 240, "rating": 4.6, "reviews": 280, "sales": 1150, "featured": False,
        "desc": "Durable stainless steel nib engineered for smooth, clean ink flow. Cylindrical contemporary brass barrel with signature Parker arrowhead pocket clip.",
        "attr": {"nib": "Fine Stainless Steel Nib", "ink": "Includes Blue Ink Cartridge + Piston Converter", "finish": "Matte Black Metal Body"},
        "images": ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "BOK-SAPIENS-HARARI",
        "name": "Sapiens: A Brief History of Humankind by Yuval Noah Harari",
        "slug": "sapiens-brief-history-of-humankind",
        "category": "books-stationery",
        "brand": "penguin",
        "seller": "eliteliving",
        "price": 449.0, "compare": 699.0, "stock": 220, "rating": 4.9, "reviews": 380, "sales": 1600, "featured": False,
        "desc": "100,000 years ago, at least six human species inhabited the earth. Today there is just one. Us. How did our species succeed in the battle for dominance?",
        "attr": {"author": "Yuval Noah Harari", "pages": "512 Pages", "genre": "History & Anthropology"},
        "images": ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "STA-LEUCHTTURM-1917-NB",
        "name": "Leuchtturm1917 Medium A5 Dotted Grid Hardcover Journal (Nordic Blue)",
        "slug": "leuchtturm1917-dotted-journal-a5",
        "category": "books-stationery",
        "brand": "moleskine",
        "seller": "eliteliving",
        "price": 2299.0, "compare": 2799.0, "stock": 75, "rating": 4.9, "reviews": 110, "sales": 340, "featured": False,
        "desc": "The favorite of bullet journalers worldwide. 251 numbered pages of 80 gsm ink-proof paper, blank table of contents, and 8 perforated tear-out sheets.",
        "attr": {"ruling": "5mm Dotted Grid", "paper": "80 gsm Ink-Proof Acid-Free", "features": "Numbered Pages + Index + Archive Stickers"},
        "images": ["https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "STA-LAMY-SAFARI-FOUNTAIN",
        "name": "LAMY Safari Charcoal Matt Finish Fountain Pen (Medium Nib, Ergonomic Grip)",
        "slug": "lamy-safari-fountain-pen-charcoal",
        "category": "books-stationery",
        "brand": "parker",
        "seller": "eliteliving",
        "price": 2690.0, "compare": 3100.0, "stock": 65, "rating": 4.8, "reviews": 140, "sales": 410, "featured": True,
        "desc": "Timeless German industrial Bauhaus design in robust ABS plastic, distinctive recessed ergonomic grip section, and spring-loaded flexible metal wire clip.",
        "attr": {"body": "Sturdy ABS Plastic Charcoal Matt", "nib": "Black Coated Stainless Steel (M)", "origin": "Made in Heidelberg, Germany"},
        "images": ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "BOK-PRAGMATIC-PROGRAMMER",
        "name": "The Pragmatic Programmer: 20th Anniversary Edition by David Thomas & Andrew Hunt",
        "slug": "the-pragmatic-programmer-20th-anniversary",
        "category": "books-stationery",
        "brand": "oreilly",
        "seller": "digitalhub",
        "price": 1299.0, "compare": 1699.0, "stock": 90, "rating": 4.9, "reviews": 170, "sales": 520, "featured": False,
        "desc": "One of the most significant books in computer science. Examines modern development practices, career wisdom, refactoring, decoupling, and testing.",
        "attr": {"authors": "David Thomas, Andrew Hunt", "pages": "352 Pages", "edition": "20th Anniversary Hardcover"},
        "images": ["https://images.unsplash.com/photo-1532012164546-f432f2e3777a?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "STA-UNI-PIN-FINELINER-6PK",
        "name": "Uni-Ball Pin Drawing Technical Fineliner Pigment Pens (Set of 6, Black Ink)",
        "slug": "uniball-pin-fineliner-pens-6pack",
        "category": "books-stationery",
        "brand": "parker",
        "seller": "eliteliving",
        "price": 599.0, "compare": 899.0, "stock": 190, "rating": 4.8, "reviews": 210, "sales": 890, "featured": False,
        "desc": "Waterproof and fade-proof Super Ink technology. Ideal for architectural sketching, calligraphy, and technical engineering drafts. Tip sizes 0.05 to 0.8mm.",
        "attr": {"pack": "6 Pens (0.05mm, 0.1mm, 0.2mm, 0.3mm, 0.5mm, 0.8mm)", "ink": "Waterproof Pigment Super Ink", "tip": "Steel-Supported Nib"},
        "images": ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "BOK-CANTHINK-HURTME-GOGGINS",
        "name": "Can't Hurt Me: Master Your Mind and Defy the Odds by David Goggins",
        "slug": "cant-hurt-me-david-goggins",
        "category": "books-stationery",
        "brand": "penguin",
        "seller": "eliteliving",
        "price": 499.0, "compare": 799.0, "stock": 210, "rating": 4.9, "reviews": 340, "sales": 1400, "featured": False,
        "desc": "For David Goggins, childhood was a nightmare. Through self-discipline, mental toughness, and hard work, he transformed into an icon of human perseverance.",
        "attr": {"author": "David Goggins (Navy SEAL)", "pages": "364 Pages", "genre": "Memoir & Mental Toughness"},
        "images": ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "STA-TOMBOW-DUAL-BRUSH-10",
        "name": "Tombow Dual Brush Art Marker Pens with Desk Stand (10-Pack Pastel Palette)",
        "slug": "tombow-dual-brush-pens-pastel-10pack",
        "category": "books-stationery",
        "brand": "parker",
        "seller": "eliteliving",
        "price": 1799.0, "compare": 2499.0, "stock": 85, "rating": 4.8, "reviews": 115, "sales": 380, "featured": False,
        "desc": "Flexible brush tip acts like a paintbrush to create fine, medium or bold strokes; fine bullet tip gives consistent lines. Water-based blendable non-toxic ink.",
        "attr": {"tips": "Dual Tip (Flexible Nylon Brush + Fine Bullet Tip)", "palette": "10 Pastel Tone Colors", "ink": "Water-Based Blendable & Acid-Free"},
        "images": ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "BOK-ZERO-TO-ONE-THIEL",
        "name": "Zero to One: Notes on Startups, or How to Build the Future by Peter Thiel",
        "slug": "zero-to-one-peter-thiel",
        "category": "books-stationery",
        "brand": "penguin",
        "seller": "eliteliving",
        "price": 379.0, "compare": 599.0, "stock": 170, "rating": 4.7, "reviews": 210, "sales": 870, "featured": False,
        "desc": "The great secret of our time is that there are still uncharted frontiers to explore. Peter Thiel shows how we can find singular ways to create new things.",
        "attr": {"author": "Peter Thiel with Blake Masters", "pages": "224 Pages", "topic": "Entrepreneurship & Innovation"},
        "images": ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "STA-ROTRING-600-PENCIL",
        "name": "rOtring 600 Mechanical Pencil 0.5mm Full Metal Body (Matte Black)",
        "slug": "rotring-600-mechanical-pencil-black",
        "category": "books-stationery",
        "brand": "parker",
        "seller": "eliteliving",
        "price": 2890.0, "compare": 3500.0, "stock": 60, "rating": 4.9, "reviews": 95, "sales": 270, "featured": True,
        "desc": "Iconic technical pencil featuring full metal body providing an ideal balance of weight and feeling. Non-slip knurled metal grip, hexagonal barrel prevents rolling.",
        "attr": {"lead_size": "0.5mm", "body": "Full Solid Brass Matte Black", "sleeve": "Fixed 4mm Lead Guidance Sleeve"},
        "images": ["https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "BOK-STEVE-JOBS-ISAACSON",
        "name": "Steve Jobs: The Exclusive Biography by Walter Isaacson",
        "slug": "steve-jobs-biography-walter-isaacson",
        "category": "books-stationery",
        "brand": "penguin",
        "seller": "eliteliving",
        "price": 549.0, "compare": 899.0, "stock": 140, "rating": 4.9, "reviews": 290, "sales": 1150, "featured": False,
        "desc": "Based on more than forty interviews with Jobs conducted over two years, as well as interviews with more than a hundred family members, friends, and competitors.",
        "attr": {"author": "Walter Isaacson", "pages": "656 Pages", "subject": "Steve Jobs / Apple Computer"},
        "images": ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "STA-KOKUYO-CAMPUS-A5-5PK",
        "name": "Kokuyo Campus Sarasara Ruled B5 Notebooks (Pack of 5 Pastel Colors)",
        "slug": "kokuyo-campus-notebooks-5pack",
        "category": "books-stationery",
        "brand": "moleskine",
        "seller": "eliteliving",
        "price": 799.0, "compare": 1299.0, "stock": 180, "rating": 4.7, "reviews": 160, "sales": 720, "featured": False,
        "desc": "Japan's best-loved student notebook. Silky smooth bleed-resistant paper allows gel pens and fountain pens to glide effortlessly without feathering.",
        "attr": {"pack": "5 Notebooks (30 Sheets / 60 Pages Each)", "paper": "Japanese Silky Sarasara Paper (70 gsm)", "ruling": "6mm Ruled with Guide Dots"},
        "images": ["https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&auto=format&fit=crop"]
    }
]
