"""
Product Catalog Dataset Part 3: Athletic Apparel + Home & Kitchen.
Authentic Indian Rupee (INR) pricing, specs, multi-vendor seller assignments.
"""

PRODUCTS_APPAREL_HOME = [
    # =========================================================================
    # 5. ATHLETIC APPAREL (26 Products)
    # =========================================================================
    {
        "sku": "APP-NIK-DRI-FIT-TEE-BLK",
        "name": "Nike Dri-FIT Men's Moisture-Wicking Training T-Shirt (Black)",
        "slug": "nike-dri-fit-training-tshirt-black",
        "category": "athletic-apparel",
        "brand": "nike",
        "seller": "urbanfit",
        "price": 1795.0, "compare": 2295.0, "stock": 140, "rating": 4.7, "reviews": 92, "sales": 510, "featured": False,
        "desc": "Soft jersey fabric with sweat-wicking Dri-FIT technology helps keep you dry, comfortable, and focused through high-intensity workout sets.",
        "attr": {"material": "100% Polyester Dri-FIT", "fit": "Standard Athletic Fit", "sleeve": "Short Sleeve", "size": "L"},
        "images": ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-ADI-OWN-THE-RUN-TEE",
        "name": "Adidas Own The Run 3-Stripes Breathable Running T-Shirt (Lucid Cyan)",
        "slug": "adidas-own-the-run-tee-cyan",
        "category": "athletic-apparel",
        "brand": "adidas",
        "seller": "urbanfit",
        "price": 1699.0, "compare": 2499.0, "stock": 115, "rating": 4.6, "reviews": 68, "sales": 340, "featured": False,
        "desc": "AEROREADY moisture-absorbing technology with 360-degree reflectivity for low-light dawn and dusk marathon training runs.",
        "attr": {"technology": "AEROREADY Moisture Absorption", "reflectivity": "360-Degree Reflective Details", "material": "Interlock Recycled Polyester"},
        "images": ["https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-PUM-ACTIVE-DRYCELL",
        "name": "Puma Active DryCELL Men's Performance Gym Tee (Medium Gray Heather)",
        "slug": "puma-active-drycell-gym-tee-gray",
        "category": "athletic-apparel",
        "brand": "puma",
        "seller": "stylemart",
        "price": 999.0, "compare": 1499.0, "stock": 180, "rating": 4.5, "reviews": 110, "sales": 620, "featured": False,
        "desc": "Equipped with dryCELL sweat-wicking designation to keep sweat away from skin, forward shoulder seams for unrestricted arm mobility in the gym.",
        "attr": {"fabric": "dryCELL 100% Polyester", "seams": "Flatlock Seams anti-friction", "neck": "Crew Neck"},
        "images": ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-UA-TECH-2-TEE",
        "name": "Under Armour Tech 2.0 Short Sleeve Training T-Shirt (Academy Navy)",
        "slug": "under-armour-tech-2-tee-navy",
        "category": "athletic-apparel",
        "brand": "under-armour",
        "seller": "urbanfit",
        "price": 1699.0, "compare": 1999.0, "stock": 125, "rating": 4.8, "reviews": 95, "sales": 410, "featured": False,
        "desc": "UA Tech fabric is quick-drying, ultra-soft & has a more natural feel. Anti-odor technology prevents the growth of odor-causing microbes.",
        "attr": {"material": "UA Tech Fabric", "odor_control": "Anti-Odor Technology", "hem": "Dropped Shaped Hem"},
        "images": ["https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-NIK-CHALLENGER-SHORTS",
        "name": "Nike Challenger Men's 7-inch Brief-Lined Running Shorts (Black)",
        "slug": "nike-challenger-7in-running-shorts",
        "category": "athletic-apparel",
        "brand": "nike",
        "seller": "urbanfit",
        "price": 2295.0, "compare": 2695.0, "stock": 90, "rating": 4.7, "reviews": 70, "sales": 310, "featured": False,
        "desc": "Lightweight woven fabric with mesh at lower side panels to stay ventilated. Discreet snap back pocket securely stashes your smartphone.",
        "attr": {"inseam": "7 inches", "liner": "Internal Brief Liner", "pockets": "Side pockets + Snap Phone Pocket"},
        "images": ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-ADI-AEROREADY-SHORTS",
        "name": "Adidas Essentials 3-Stripes Chelsea Shorts (Legend Ink)",
        "slug": "adidas-essentials-chelsea-shorts",
        "category": "athletic-apparel",
        "brand": "adidas",
        "seller": "stylemart",
        "price": 1499.0, "compare": 2299.0, "stock": 110, "rating": 4.5, "reviews": 85, "sales": 430, "featured": False,
        "desc": "Classic 3-Stripes running shorts made with moisture-wicking AEROREADY plain weave fabric, internal drawcord on elastic waist, and slip-in side pockets.",
        "attr": {"waist": "Drawcord Elastic", "pockets": "Dual Side Pockets", "fabric": "100% Recycled Polyester"},
        "images": ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-PUM-TRAINING-SHORTS",
        "name": "Puma Men's Training Knit 8-inch Gym Shorts (Puma Black)",
        "slug": "puma-training-knit-8in-shorts",
        "category": "athletic-apparel",
        "brand": "puma",
        "seller": "stylemart",
        "price": 1299.0, "compare": 1999.0, "stock": 130, "rating": 4.4, "reviews": 60, "sales": 360, "featured": False,
        "desc": "Breathable French Terry knit construction engineered for squats, box jumps, and functional fitness routines with ergonomic side slits.",
        "attr": {"fabric": "French Terry Knit", "slits": "Side Mobility Slits", "pockets": "Deep Hand Pockets"},
        "images": ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-NIK-THERMA-FIT-HOODIE",
        "name": "Nike Therma-FIT Men's Fleece Training Pullover Hoodie (Dark Grey Heather)",
        "slug": "nike-therma-fit-fleece-hoodie-grey",
        "category": "athletic-apparel",
        "brand": "nike",
        "seller": "urbanfit",
        "price": 3495.0, "compare": 4295.0, "stock": 70, "rating": 4.8, "reviews": 84, "sales": 280, "featured": True,
        "desc": "Therma-FIT technology helps manage your body's natural heat to keep you warm in cold-weather outdoor drills, featuring front kangaroo pocket and drawcord hood.",
        "attr": {"technology": "Therma-FIT Heat Retention", "interior": "Soft Brushed Fleece", "pocket": "Kangaroo Front Pouch"},
        "images": ["https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-ADI-ESSENTIALS-HOODIE",
        "name": "Adidas Essentials French Terry 3-Stripes Full-Zip Hoodie (Black)",
        "slug": "adidas-essentials-3-stripes-zip-hoodie",
        "category": "athletic-apparel",
        "brand": "adidas",
        "seller": "stylemart",
        "price": 2999.0, "compare": 4599.0, "stock": 85, "rating": 4.7, "reviews": 110, "sales": 390, "featured": False,
        "desc": "A post-workout staple cut in cotton-blend French terry. Full zip front lets you layer easily, ribbed cuffs and hem keep chilly air at bay.",
        "attr": {"closure": "Full Length Front Zipper", "material": "70% Cotton / 30% Recycled Poly French Terry", "hood": "Adjustable Drawcord"},
        "images": ["https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-PUM-EVOSTRIPE-JACKET",
        "name": "Puma Evostripe Full-Zip Men's Training Jacket (Castlerock Heather)",
        "slug": "puma-evostripe-training-jacket",
        "category": "athletic-apparel",
        "brand": "puma",
        "seller": "urbanfit",
        "price": 3299.0, "compare": 4999.0, "stock": 75, "rating": 4.6, "reviews": 55, "sales": 220, "featured": False,
        "desc": "Evostripe cutlines with articulation through the arms for improved flexibility. Raglan sleeves, zip chin guard, and zippered side security pockets.",
        "attr": {"cut": "Evostripe Articulated Cutline", "pockets": "Dual Secure Zip Pockets", "fabric": "dryCELL Poly-Cotton"},
        "images": ["https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-NIK-WINDRUNNER-JKT",
        "name": "Nike Sportswear Windrunner Hooded Running Jacket (Game Royal / White)",
        "slug": "nike-windrunner-jacket-royal-blue",
        "category": "athletic-apparel",
        "brand": "nike",
        "seller": "urbanfit",
        "price": 5495.0, "compare": 6495.0, "stock": 45, "rating": 4.9, "reviews": 90, "sales": 320, "featured": True,
        "desc": "Iconic 26-degree chevron design on the chest. Woven water-repellent fabric helps shed light rain showers while back vent boosts air circulation.",
        "attr": {"weather": "Water-Repellent Lightweight Woven", "design": "Classic 1978 Chevron Styling", "hood": "Adjustable Scuba Hood"},
        "images": ["https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-ADI-TIRO-23-PANTS",
        "name": "Adidas Tiro 23 League Tapered Training Track Pants (Black / White)",
        "slug": "adidas-tiro-23-league-track-pants",
        "category": "athletic-apparel",
        "brand": "adidas",
        "seller": "urbanfit",
        "price": 2799.0, "compare": 3999.0, "stock": 95, "rating": 4.8, "reviews": 140, "sales": 560, "featured": False,
        "desc": "Born on the pitch, worn everywhere. Ankle zips make them easy to pull on over football boots or running trainers. AEROREADY moisture management.",
        "attr": {"fit": "Tapered Ankle Fit", "features": "Lower Leg Ankle Zips", "technology": "AEROREADY"},
        "images": ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-PUM-CLASSIC-TRACKPANTS",
        "name": "Puma Men's Poly Track Pants with Contrast Piping (Navy Peacoat)",
        "slug": "puma-poly-track-pants-navy",
        "category": "athletic-apparel",
        "brand": "puma",
        "seller": "stylemart",
        "price": 1899.0, "compare": 2999.0, "stock": 110, "rating": 4.5, "reviews": 75, "sales": 380, "featured": False,
        "desc": "Comfortable polyester knit with elasticated waistband and internal drawstrings, open bottom hem for casual drape over sneakers.",
        "attr": {"fabric": "100% Polyester Warp Knit", "closure": "Elastic with Drawcord", "fit": "Regular Straight Leg"},
        "images": ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-UA-HEATGEAR-LONG",
        "name": "Under Armour HeatGear Men's Compression Long Sleeve Shirt (Black)",
        "slug": "under-armour-heatgear-compression-long-sleeve",
        "category": "athletic-apparel",
        "brand": "under-armour",
        "seller": "fitzone",
        "price": 2499.0, "compare": 2999.0, "stock": 80, "rating": 4.8, "reviews": 90, "sales": 340, "featured": False,
        "desc": "Original performance baselayer that you put on first and take off last. Tight compression fit supports active muscles and speeds recovery.",
        "attr": {"fit": "Ultra-Tight Compression Second-Skin", "mesh": "Strategic Mesh Underarm Ventilation", "sun": "UPF 30+ UV Protection"},
        "images": ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-NIK-PRO-TIGHTS",
        "name": "Nike Pro Men's Full-Length Training Compression Tights (Black)",
        "slug": "nike-pro-mens-compression-tights",
        "category": "athletic-apparel",
        "brand": "nike",
        "seller": "fitzone",
        "price": 2395.0, "compare": 2895.0, "stock": 85, "rating": 4.8, "reviews": 82, "sales": 310, "featured": False,
        "desc": "Nike Pro fabric with sweat-wicking technology helps you feel locked-in and cool when intensity heats up. Stretchy, lightweight fabric moves with you.",
        "attr": {"waistband": "Snug Elastic Nike Pro Band", "flat_seams": "Smooth Frictionless Seams", "pockets": "Media Device Drop-In Pocket"},
        "images": ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-ADI-RUN-IT-TANK",
        "name": "Adidas Run It Sleeveless Running Tank Top (Preloved Ink)",
        "slug": "adidas-run-it-running-tank",
        "category": "athletic-apparel",
        "brand": "adidas",
        "seller": "urbanfit",
        "price": 1299.0, "compare": 1999.0, "stock": 105, "rating": 4.6, "reviews": 45, "sales": 230, "featured": False,
        "desc": "Featherlight sleeveless running singlet designed for humid summer runs. Deep armholes ensure zero chafe across high mileage workouts.",
        "attr": {"cut": "Athletic Singlet Tank", "technology": "AEROREADY Breathable Mesh", "reflectors": "High-Visibility Bars"},
        "images": ["https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-PUM-FAVORITE-TEE",
        "name": "Puma Favorite Men's Heather Running T-Shirt (Sun Stream Orange)",
        "slug": "puma-favorite-running-tshirt-orange",
        "category": "athletic-apparel",
        "brand": "puma",
        "seller": "urbanfit",
        "price": 1199.0, "compare": 1699.0, "stock": 120, "rating": 4.5, "reviews": 50, "sales": 270, "featured": False,
        "desc": "Built for high performance with ergonomic cutlines, lightweight heather jersey, and 360-degree reflectivity for visibility in dusky conditions.",
        "attr": {"fabric": "Heather dryCELL Poly-Elastane", "details": "Reflective Cat Logo", "feel": "Silky Lightweight Touch"},
        "images": ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-UA-SPORTSTYLE-JOGGER",
        "name": "Under Armour Sportstyle Cotton-Blend Fleece Joggers (Pitch Gray Light)",
        "slug": "under-armour-sportstyle-fleece-jogger",
        "category": "athletic-apparel",
        "brand": "under-armour",
        "seller": "stylemart",
        "price": 3199.0, "compare": 4499.0, "stock": 70, "rating": 4.7, "reviews": 68, "sales": 250, "featured": False,
        "desc": "Durable knit fabric with a smooth face and a soft inner to trap warmth. Ribbed cuffs and waistband with external drawcord, secure snap back pocket.",
        "attr": {"cuffs": "Ribbed Ankle Cuffs", "interior": "Soft Brushed Fleece", "pockets": "Hand Pockets + Right Back Snap Pocket"},
        "images": ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-NIK-MILER-SS-TOP",
        "name": "Nike Dri-FIT Miler Short-Sleeve Running Top (Volt Yellow / Reflective)",
        "slug": "nike-dri-fit-miler-top-volt",
        "category": "athletic-apparel",
        "brand": "nike",
        "seller": "fitzone",
        "price": 1995.0, "compare": 2495.0, "stock": 90, "rating": 4.7, "reviews": 74, "sales": 330, "featured": False,
        "desc": "Crimped yarn creates airflow to help keep you cool. Soft feel helps cut down on chafing on your longest running workouts under the sun.",
        "attr": {"protection": "UVA and UVB Protection in Covered Areas", "shoulder_seams": "Rolled-Forward Seams", "color": "High-Visibility Volt"},
        "images": ["https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-ADI-PRIMEBLUE-JACKET",
        "name": "Adidas Marathon Primeblue Running Windbreaker Jacket (Black / Reflective)",
        "slug": "adidas-marathon-primeblue-jacket",
        "category": "athletic-apparel",
        "brand": "adidas",
        "seller": "urbanfit",
        "price": 4999.0, "compare": 6999.0, "stock": 45, "rating": 4.8, "reviews": 58, "sales": 190, "featured": False,
        "desc": "Wind-resistant and breathable running jacket made featuring Parley Ocean Plastic upcycled marine waste, with packable chest pocket design.",
        "attr": {"material": "Primeblue with Parley Ocean Plastic", "features": "Packable into Internal Pocket", "resistance": "Wind-Resistant DWR"},
        "images": ["https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-PUM-POWER-FLEECE-PANT",
        "name": "Puma Power Colorblock Fleece Sweatpants (Puma Black / High Risk Red)",
        "slug": "puma-power-colorblock-sweatpants",
        "category": "athletic-apparel",
        "brand": "puma",
        "seller": "stylemart",
        "price": 1799.0, "compare": 2799.0, "stock": 95, "rating": 4.5, "reviews": 62, "sales": 290, "featured": False,
        "desc": "Bold street-ready colorblock panels across the calves, cozy cotton-rich fleece interior, and relaxed athletic silhouette for downtime rest days.",
        "attr": {"colorblock": "Contrast Calf Panel Detailing", "interior": "Brushed Warm Fleece", "fit": "Tapered Jogger"},
        "images": ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-UA-ISOBHILL-POLO",
        "name": "Under Armour Iso-Chill Men's Performance Golf Polo (White / Mod Gray)",
        "slug": "under-armour-iso-chill-golf-polo",
        "category": "athletic-apparel",
        "brand": "under-armour",
        "seller": "stylemart",
        "price": 3499.0, "compare": 4499.0, "stock": 60, "rating": 4.8, "reviews": 46, "sales": 180, "featured": False,
        "desc": "Iso-Chill fabric pulls heat away from your skin so you feel cooler and can play longer. 4-way stretch material moves better in every direction.",
        "attr": {"cooling": "Iso-Chill Heat Dispersion Fabric", "collar": "Low-Profile Modern Blade Collar", "stretch": "4-Way Stretch Construction"},
        "images": ["https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-NIK-CLUB-FLEECE-CREW",
        "name": "Nike Sportswear Club Fleece Crewneck Sweatshirt (Midnight Navy)",
        "slug": "nike-club-fleece-crewneck-navy",
        "category": "athletic-apparel",
        "brand": "nike",
        "seller": "stylemart",
        "price": 2895.0, "compare": 3495.0, "stock": 80, "rating": 4.7, "reviews": 95, "sales": 360, "featured": False,
        "desc": "An essential wardrobe staple crafted from brushed-back fleece for a smooth exterior and super soft plush interior, with embroidered Nike Futura logo.",
        "attr": {"style": "Crewneck Pullover", "fleece": "Brushed-Back Cotton Fleece", "cuffs": "Ribbed Hem & Cuffs"},
        "images": ["https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-ADI-RUN-SOCKS-3PK",
        "name": "Adidas Performance Cushioned Quarter Running Socks (3-Pack, White)",
        "slug": "adidas-cushioned-quarter-socks-3pack",
        "category": "athletic-apparel",
        "brand": "adidas",
        "seller": "urbanfit",
        "price": 799.0, "compare": 1199.0, "stock": 210, "rating": 4.6, "reviews": 180, "sales": 890, "featured": False,
        "desc": "Heel-to-toe cushioning protects feet during intense road workouts. Arch support band hugs the midfoot for an unshakeable blister-free fit.",
        "attr": {"pack": "3 Pairs Included", "cushioning": "Targeted Sole Cushioning", "support": "Compression Arch Support"},
        "images": ["https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-NIK-EVERYDAY-SOCKS",
        "name": "Nike Everyday Plus Cushioned Crew Training Socks (3-Pair Pack, Black)",
        "slug": "nike-everyday-cushioned-crew-socks-3pack",
        "category": "athletic-apparel",
        "brand": "nike",
        "seller": "urbanfit",
        "price": 995.0, "compare": 1295.0, "stock": 240, "rating": 4.8, "reviews": 230, "sales": 1100, "featured": False,
        "desc": "Dri-FIT technology helps your feet stay dry and comfortable. Cushioning at key points underfoot dampens impact on gym floor drills.",
        "attr": {"height": "Crew Length", "pack": "3 Pairs", "features": "Reinforced Heel and Toe for Durability"},
        "images": ["https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "APP-PUM-GYM-DUFFEL-BAG",
        "name": "Puma Evercat Contender 30L Sports Gym Duffel Bag (Black / Silver)",
        "slug": "puma-evercat-gym-duffel-bag",
        "category": "athletic-apparel",
        "brand": "puma",
        "seller": "urbanfit",
        "price": 1499.0, "compare": 2499.0, "stock": 100, "rating": 4.6, "reviews": 85, "sales": 390, "featured": False,
        "desc": "Spacious 30-liter compartment with dedicated ventilated side shoe compartment, padded adjustable shoulder strap, and water-resistant base panel.",
        "attr": {"capacity": "30 Liters", "compartments": "Ventilated Shoe Pocket + Mesh Bottle Pocket", "base": "Water-Resistant Coated Base"},
        "images": ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop"]
    },

    # =========================================================================
    # 6. HOME & KITCHEN (26 Products)
    # =========================================================================
    {
        "sku": "HOM-PRL-ESPRESSO-15",
        "name": "PureLiving Barista Pro 15-Bar Stainless Steel Espresso Machine",
        "slug": "pureliving-barista-pro-espresso-machine",
        "category": "home-kitchen",
        "brand": "philips",
        "seller": "pureliving",
        "price": 12499.0, "compare": 16999.0, "stock": 35, "rating": 4.8, "reviews": 48, "sales": 130, "featured": True,
        "desc": "Café-quality espresso at home with thermo-block rapid heating, precision commercial steam wand for silky microfoam, and 15-bar Italian pump.",
        "attr": {"pump": "15-Bar High Pressure Italian Pump", "water_tank": "1.8L Removable Reservoir", "body": "Brushed Stainless Steel", "extras": "Dual Filter Baskets + Tamper"},
        "images": ["https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-PHI-AIRFRYER-HD9252",
        "name": "Philips Digital Air Fryer HD9252 with Rapid Air Technology (4.1L, Black)",
        "slug": "philips-digital-air-fryer-hd9252",
        "category": "home-kitchen",
        "brand": "philips",
        "seller": "kitchenkart",
        "price": 8999.0, "compare": 12995.0, "stock": 65, "rating": 4.8, "reviews": 160, "sales": 520, "featured": True,
        "desc": "Cook with up to 90% less fat thanks to Rapid Air starfish design. Touch screen with 7 presets including frozen snacks, fresh fries, meat, fish, and baking.",
        "attr": {"capacity": "4.1 Liters", "power": "1400 Watts", "presets": "7 One-Touch Digital Presets", "features": "Keep Warm Function"},
        "images": ["https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-PRE-IRIS-MIXER-750",
        "name": "Prestige Iris 750 Watt Mixer Grinder with 3 Stainless Steel Jars + Juicer Jar",
        "slug": "prestige-iris-750w-mixer-grinder",
        "category": "home-kitchen",
        "brand": "prestige",
        "seller": "kitchenkart",
        "price": 3199.0, "compare": 6295.0, "stock": 140, "rating": 4.5, "reviews": 290, "sales": 1200, "featured": False,
        "desc": "Heavy-duty 750W motor tackles tough Indian spices like turmeric. Includes 1.5L wet jar, 1.0L dry jar, 300ml chutney jar, and transparent juicer jar.",
        "attr": {"motor": "750 Watt Copper Motor", "jars": "4 Jars (3 Stainless Steel + 1 Juicer)", "blades": "Multi-function Stainless Blades"},
        "images": ["https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-HAV-AQUA-PLUS-KETTLE",
        "name": "Havells Aqua Plus 1.2L Double Wall Stainless Steel Electric Kettle (Cool Touch)",
        "slug": "havells-aqua-plus-electric-kettle",
        "category": "home-kitchen",
        "brand": "havells",
        "seller": "kitchenkart",
        "price": 1499.0, "compare": 2995.0, "stock": 180, "rating": 4.6, "reviews": 210, "sales": 850, "featured": False,
        "desc": "Cool-touch outer body prevents burns while 304 food-grade stainless steel interior ensures zero plastic contact with boiling water. Auto shut-off safety.",
        "attr": {"capacity": "1.2 Liters", "material": "Double Wall 304 Stainless Steel", "power": "1500 Watts", "safety": "Auto Shut-Off & Dry Boil Protection"},
        "images": ["https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-PRE-COOKWARE-3PC",
        "name": "Prestige Omega Deluxe Granite 3-Piece Non-Stick Cookware Set with Glass Lids",
        "slug": "prestige-omega-deluxe-cookware-3pc",
        "category": "home-kitchen",
        "brand": "prestige",
        "seller": "kitchenkart",
        "price": 2899.0, "compare": 5150.0, "stock": 90, "rating": 4.6, "reviews": 140, "sales": 610, "featured": False,
        "desc": "5-layer durable granite finish coating made with German technology. Induction and gas stove compatible. Includes 240mm Omni Tawa, 240mm Fry Pan, and 240mm Kadai.",
        "attr": {"set": "Tawa (24cm) + Fry Pan (24cm) + Kadai with Glass Lid", "coating": "5-Layer Scratch Resistant Granite", "base": "Induction & Gas Compatible"},
        "images": ["https://images.unsplash.com/photo-1584990347449-397cf1e9fb7b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-DYS-V8-ABSOLUTE",
        "name": "Dyson V8 Absolute Cordless Vacuum Cleaner with De-Tangling Motorbar",
        "slug": "dyson-v8-absolute-cordless-vacuum",
        "category": "home-kitchen",
        "brand": "dyson",
        "seller": "pureliving",
        "price": 29900.0, "compare": 42900.0, "stock": 25, "rating": 4.9, "reviews": 75, "sales": 190, "featured": True,
        "desc": "Powerful suction engineered for homes with pets. Up to 40 minutes fade-free power, whole-machine advanced filtration capturing 99.99% of microscopic particles.",
        "attr": {"runtime": "Up to 40 Minutes", "suction": "115 AW Strong Suction", "filtration": "Whole Machine HEPA Filtration", "weight": "2.5 kg"},
        "images": ["https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-PHI-GC181-IRON",
        "name": "Philips GC181 Heavy-Weight 1000W Dry Iron with Non-Stick Black Coating",
        "slug": "philips-gc181-heavy-weight-dry-iron",
        "category": "home-kitchen",
        "brand": "philips",
        "seller": "kitchenkart",
        "price": 1099.0, "compare": 1595.0, "stock": 220, "rating": 4.6, "reviews": 310, "sales": 1450, "featured": False,
        "desc": "1.6kg heavy soleplate effortlessly flattens tough creases on cotton shirts and linen sarees without pressing hard, uniform thermostatic heat control.",
        "attr": {"weight": "1.6 kg Heavyweight Soleplate", "power": "1000 Watts", "soleplate": "Black American Heritage Non-Stick"},
        "images": ["https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-HAV-INSTA-INDUCTION",
        "name": "Havells Insta Cook ET-X 1900W Induction Cooktop with 8 Auto Cooking Modes",
        "slug": "havells-insta-cook-1900w-induction",
        "category": "home-kitchen",
        "brand": "havells",
        "seller": "kitchenkart",
        "price": 2799.0, "compare": 5195.0, "stock": 110, "rating": 4.5, "reviews": 125, "sales": 540, "featured": False,
        "desc": "1900W high power rapid heating with full ceramic glass top, Indian preset cooking menus (Curry, Dosa, Idli, Milk, Boil), and 3-hour digital timer.",
        "attr": {"power": "1900 Watts", "panel": "Microcrystalline Ceramic Glass Top", "presets": "8 Auto Cooking Menus", "timer": "3 Hours Digital"},
        "images": ["https://images.unsplash.com/photo-1584990347449-397cf1e9fb7b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-PRE-SVACHH-PRESSURE-5L",
        "name": "Prestige Svachh Hard Anodized 5L Deep Pressure Cooker with Spillage Control",
        "slug": "prestige-svachh-5l-pressure-cooker",
        "category": "home-kitchen",
        "brand": "prestige",
        "seller": "kitchenkart",
        "price": 2499.0, "compare": 3670.0, "stock": 125, "rating": 4.7, "reviews": 190, "sales": 820, "featured": False,
        "desc": "Revolutionary Svachh lid controls froth spillage onto the kitchen counter. Hard anodized body for superior durability, induction and gas friendly base.",
        "attr": {"capacity": "5.0 Liters", "material": "Hard Anodized Aluminum", "lid": "Svachh Deep Spillage-Control Lid"},
        "images": ["https://images.unsplash.com/photo-1584990347449-397cf1e9fb7b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-PHI-POWERCHOP-FOOD-PROC",
        "name": "Philips Daily Collection 650W Food Processor with PowerChop Technology",
        "slug": "philips-daily-collection-food-processor",
        "category": "home-kitchen",
        "brand": "philips",
        "seller": "kitchenkart",
        "price": 5499.0, "compare": 7995.0, "stock": 55, "rating": 4.6, "reviews": 88, "sales": 290, "featured": False,
        "desc": "PowerChop technology combines blade shape, cutting angle and inner bowl for superior chopping of hard and soft ingredients. Includes slicing/shredding discs and kneading tool.",
        "attr": {"power": "650 Watts", "bowl_capacity": "2.1 Liters", "accessories": "Slicing, Shredding, Kneading, Emulsifying"},
        "images": ["https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-DYS-PURIFIER-HOT-COOL",
        "name": "Dyson Purifier Hot+Cool Gen1 Air Purifier with HEPA H13 Filtration",
        "slug": "dyson-purifier-hot-cool-gen1",
        "category": "home-kitchen",
        "brand": "dyson",
        "seller": "pureliving",
        "price": 43900.0, "compare": 56900.0, "stock": 18, "rating": 4.9, "reviews": 52, "sales": 110, "featured": True,
        "desc": "Automatically senses and captures 99.95% of pollutants down to 0.1 microns. Air Multiplier technology purifies and heats or cools the whole room.",
        "attr": {"filtration": "HEPA H13 Fully Sealed Standard", "functions": "Air Purification + Ceramic Heating + Fan Cooling", "oscillation": "350 Degrees"},
        "images": ["https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-MILTON-THERMOSTEEL-1L",
        "name": "Milton Thermosteel Flip Lid 1000ml Insulated Water Flask Bottle",
        "slug": "milton-thermosteel-1000ml-flask",
        "category": "home-kitchen",
        "brand": "prestige",
        "seller": "homeessentials",
        "price": 999.0, "compare": 1420.0, "stock": 260, "rating": 4.7, "reviews": 410, "sales": 1850, "featured": False,
        "desc": "Double-wall vacuum insulation keeps beverages hot or cold for 24 hours. Fabricated inside and outside in 18/8 quality stainless steel with leak-proof flip lid.",
        "attr": {"capacity": "1000ml (1 Liter)", "retention": "Hot or Cold for 24 Hours", "material": "18/8 Food Grade Rustproof Steel"},
        "images": ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-WIPRO-SMART-LED-9W",
        "name": "Wipro Garnet 9W B22 WiFi Smart LED RGB Bulb (16 Million Colors, Music Sync)",
        "slug": "wipro-garnet-9w-smart-bulb",
        "category": "home-kitchen",
        "brand": "havells",
        "seller": "homeessentials",
        "price": 599.0, "compare": 1099.0, "stock": 310, "rating": 4.4, "reviews": 380, "sales": 1600, "featured": False,
        "desc": "Voice control with Alexa and Google Assistant. Choose between 16 million colors, tune between warm white and cool daylight (2700K to 6500K).",
        "attr": {"wattage": "9 Watts (B22 Base)", "connectivity": "Direct Wi-Fi 2.4GHz (No Hub Required)", "colors": "16 Million RGB Colors + CCT Tunable White"},
        "images": ["https://images.unsplash.com/photo-1550985543-f47f38aeee65?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-WAKEFIT-PILLOW-2PK",
        "name": "Wakefit Sleeping Hollow Fibre Reversible Pillow (Set of 2, White)",
        "slug": "wakefit-fibre-pillow-pack-of-2",
        "category": "home-kitchen",
        "brand": "pureliving",
        "seller": "homeessentials",
        "price": 849.0, "compare": 1599.0, "stock": 190, "rating": 4.6, "reviews": 290, "sales": 1250, "featured": False,
        "desc": "200 GSM breathable spun polyester fabric filled with premium hollow conjugate siliconized fiber for optimal cervical neck alignment and plush bounce.",
        "attr": {"pack": "Set of 2 Pillows", "filling": "Hollow Siliconized Conjugate Fibre", "dimensions": "27 inch x 17 inch"},
        "images": ["https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-BOMBAY-BEDSHEET-DBL",
        "name": "Bombay Dyeing 100% Pure Cotton Double Bedsheet with 2 Pillow Covers (Blue Floral)",
        "slug": "bombay-dyeing-cotton-double-bedsheet-blue",
        "category": "home-kitchen",
        "brand": "pureliving",
        "seller": "homeessentials",
        "price": 1499.0, "compare": 2499.0, "stock": 140, "rating": 4.5, "reviews": 160, "sales": 690, "featured": False,
        "desc": "Crafted from long-staple combed cotton with 180 thread count, breathable soft feel, color-fast non-fading dyes, and machine washable durability.",
        "attr": {"thread_count": "180 TC", "material": "100% Combed Cotton", "dimensions": "Bedsheet: 220 x 240 cm + 2 Pillow Covers: 46 x 69 cm"},
        "images": ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-PHI-HAND-BLENDER-250",
        "name": "Philips Daily Collection 250W Hand Blender with Whisk & Beaker (White)",
        "slug": "philips-daily-hand-blender-250w",
        "category": "home-kitchen",
        "brand": "philips",
        "seller": "kitchenkart",
        "price": 1699.0, "compare": 2195.0, "stock": 115, "rating": 4.5, "reviews": 140, "sales": 580, "featured": False,
        "desc": "Specially designed blade for smooth purees, baby food, and shakes without splash. Rustproof stainless steel blending bar with ergonomic single-button control.",
        "attr": {"power": "250 Watts", "rod": "Stainless Steel Anti-Splash Rod", "accessories": "Measuring Beaker Included"},
        "images": ["https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-HAV-GLAZE-750-RO",
        "name": "Havells Glaze 750W 3-Jar Mixer Grinder with Copper Motor (Burgundy)",
        "slug": "havells-glaze-750w-mixer-grinder",
        "category": "home-kitchen",
        "brand": "havells",
        "seller": "kitchenkart",
        "price": 3499.0, "compare": 5895.0, "stock": 80, "rating": 4.6, "reviews": 95, "sales": 390, "featured": False,
        "desc": "Heavy-duty ball-bearing copper motor with dual exhaust air cooling for prolonged grinding of thick batters without motor trips. 3 stainless jars.",
        "attr": {"motor": "750W 100% Copper Motor", "jars": "1.5L Wet Jar + 1.0L Dry Jar + 400ml Chutney Jar", "speed": "3 Speeds + Pulse"},
        "images": ["https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-PRE-NAKSHATRA-3L",
        "name": "Prestige Nakshatra Plus 3-Liter Hard Anodized Inner Lid Pressure Handi",
        "slug": "prestige-nakshatra-3l-handi",
        "category": "home-kitchen",
        "brand": "prestige",
        "seller": "kitchenkart",
        "price": 1899.0, "compare": 2720.0, "stock": 105, "rating": 4.6, "reviews": 110, "sales": 480, "featured": False,
        "desc": "Unique handi curved body shape promotes easy stirring and deep aroma infusion for biryanis, curries, and dals. Induction compatible thick base.",
        "attr": {"shape": "Traditional Curved Handi Shape", "capacity": "3.0 Liters", "lid": "Inner Lid Mechanism"},
        "images": ["https://images.unsplash.com/photo-1584990347449-397cf1e9fb7b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-HAV-OTG-28L",
        "name": "Havells Airfryer OTG 28-Litre with 360-Degree Convection & Rotisserie",
        "slug": "havells-airfryer-otg-28l-rotisserie",
        "category": "home-kitchen",
        "brand": "havells",
        "seller": "kitchenkart",
        "price": 9999.0, "compare": 15995.0, "stock": 35, "rating": 4.7, "reviews": 60, "sales": 170, "featured": False,
        "desc": "Combines full oven-toaster-grill functions with high-velocity air fryer basket for oil-free crispy chicken wings, homemade sourdough, and grilled paneer.",
        "attr": {"capacity": "28 Liters", "power": "1600 Watts", "accessories": "Rotisserie Spit + Airfryer Basket + Baking Tray"},
        "images": ["https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-PHI-CITRUS-PRESS-JUICER",
        "name": "Philips Citrus Press Juicer HR2775 with Pulp Selector (1 Liter, White)",
        "slug": "philips-citrus-press-juicer",
        "category": "home-kitchen",
        "brand": "philips",
        "seller": "kitchenkart",
        "price": 1299.0, "compare": 1795.0, "stock": 130, "rating": 4.5, "reviews": 115, "sales": 470, "featured": False,
        "desc": "Extract maximum juice from sweet limes, oranges, and grapefruits with adjustable pulp selector switch and automatic two-way cone rotation.",
        "attr": {"capacity": "1.0 Liter Juicer Jug", "rotation": "Two-Way Auto Reverse", "pulp": "Adjustable Pulp Density Filter"},
        "images": ["https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-PRE-EDGE-KNIFE-SET",
        "name": "Prestige Tru-Edge 5-Piece Kitchen Knife Set with Wooden Countertop Block",
        "slug": "prestige-tru-edge-knife-set-5pc",
        "category": "home-kitchen",
        "brand": "prestige",
        "seller": "homeessentials",
        "price": 999.0, "compare": 1695.0, "stock": 160, "rating": 4.5, "reviews": 180, "sales": 730, "featured": False,
        "desc": "High-carbon stainless steel blades tempered for edge retention. Includes chef knife, slicer, utility knife, paring knife, and kitchen shears in wooden stand.",
        "attr": {"blades": "High-Carbon Tempered Stainless Steel", "block": "Solid Hardwood Countertop Block", "handles": "Full-Tang Riveted Handles"},
        "images": ["https://images.unsplash.com/photo-1584990347449-397cf1e9fb7b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-MILTON-LUNCHBOX-3",
        "name": "Milton Executive Insulated Stainless Steel Lunch Box Set (3 Containers + Bag)",
        "slug": "milton-executive-lunch-box-3-containers",
        "category": "home-kitchen",
        "brand": "prestige",
        "seller": "homeessentials",
        "price": 899.0, "compare": 1250.0, "stock": 210, "rating": 4.6, "reviews": 240, "sales": 1050, "featured": False,
        "desc": "Leak-resistant airtight containers made of food-grade stainless steel with thermal insulated fabric jacket that keeps food warm for office lunch breaks.",
        "attr": {"containers": "2 Round Steel Containers (280ml) + 1 Oval Steel (450ml)", "carrier": "Thermal Insulated Washable Carry Bag"},
        "images": ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-HAV-VENTILAIR-EXHAUST",
        "name": "Havells Ventil Air DB 200mm High-Performance Kitchen Exhaust Fan (Pewter Gray)",
        "slug": "havells-ventil-air-exhaust-fan-200mm",
        "category": "home-kitchen",
        "brand": "havells",
        "seller": "homeessentials",
        "price": 1599.0, "compare": 2350.0, "stock": 120, "rating": 4.5, "reviews": 85, "sales": 360, "featured": False,
        "desc": "Heavy-duty double ball-bearing motor with automatic back-shutters that close when switched off to prevent insects and lizards from entering.",
        "attr": {"sweep": "200mm (8 inch)", "shutters": "Gravity Automatic Rear Shutters", "motor": "Double Ball Bearing 100% Copper"},
        "images": ["https://images.unsplash.com/photo-1550985543-f47f38aeee65?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-WAKEFIT-SHEET-FITTED",
        "name": "Wakefit All-Round Elastic Fitted Double King Bedsheet with 2 Pillow Covers (Sage Green)",
        "slug": "wakefit-fitted-bedsheet-sage-green",
        "category": "home-kitchen",
        "brand": "pureliving",
        "seller": "homeessentials",
        "price": 1299.0, "compare": 1999.0, "stock": 150, "rating": 4.7, "reviews": 195, "sales": 740, "featured": False,
        "desc": "360-degree all-around elastic border grips deep mattresses up to 10 inches thick so you never have to tuck corners every morning. 100% combed cotton.",
        "attr": {"pocket_depth": "Fits up to 10-inch Mattresses", "material": "100% Combed Cotton 210 TC", "elastic": "Heavy Duty 360 Elastic"},
        "images": ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-PRL-WOODEN-ORGANIZER",
        "name": "PureLiving Multi-Tier Natural Bamboo Kitchen Countertop Spice Rack & Organizer",
        "slug": "pureliving-bamboo-spice-rack-organizer",
        "category": "home-kitchen",
        "brand": "pureliving",
        "seller": "eliteliving",
        "price": 1499.0, "compare": 2299.0, "stock": 85, "rating": 4.7, "reviews": 90, "sales": 320, "featured": False,
        "desc": "Sustainable Moso bamboo step organizer keeps spice jars, oils, and vinegar bottles visible and within arm's reach on kitchen counters or pantry shelves.",
        "attr": {"material": "100% Organic Bamboo Wood", "tiers": "3-Tier Stepped Stadium Design", "finish": "Water-Resistant Natural Polish"},
        "images": ["https://images.unsplash.com/photo-1584990347449-397cf1e9fb7b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "HOM-PRE-MILK-COOKER-1L",
        "name": "Prestige Stainless Steel 1.0L Double Wall Whistling Milk Boiler Cooker",
        "slug": "prestige-stainless-steel-milk-boiler-1l",
        "category": "home-kitchen",
        "brand": "prestige",
        "seller": "kitchenkart",
        "price": 1199.0, "compare": 1720.0, "stock": 170, "rating": 4.6, "reviews": 150, "sales": 640, "featured": False,
        "desc": "Double-wall water chamber boils milk gently without burning or spilling over. Built-in steam whistle alerts you the moment milk has reached a rolling boil.",
        "attr": {"capacity": "1.0 Liter", "alert": "Acoustic Steam Whistle", "body": "Mirror-Polished Surgical Grade Stainless Steel"},
        "images": ["https://images.unsplash.com/photo-1584990347449-397cf1e9fb7b?w=800&auto=format&fit=crop"]
    }
]
