"""
Product Catalog Dataset Part 2: Audio & Wearables + Footwear & Running.
Authentic Indian Rupee (INR) pricing, specs, multi-vendor seller assignments.
"""

PRODUCTS_AUDIO_FOOTWEAR = [
    # =========================================================================
    # 3. AUDIO & WEARABLES (26 Products)
    # =========================================================================
    {
        "sku": "AUD-SNY-WH1000XM5-BLK",
        "name": "Sony WH-1000XM5 Wireless Industry Leading Noise Canceling Headphones (Black)",
        "slug": "sony-wh-1000xm5-noise-canceling-black",
        "category": "audio-wearables",
        "brand": "sony",
        "seller": "audioplanet",
        "price": 28990.0, "compare": 34990.0, "stock": 85, "rating": 4.9, "reviews": 168, "sales": 420, "featured": True,
        "desc": "Industry-leading noise cancellation with two processors and 8 microphones. High-Resolution Audio with 30-hour battery life and ultra-comfortable lightweight design.",
        "attr": {"form_factor": "Over-Ear", "anc": "HD Noise Canceling QN1 + V1", "battery_life": "30 Hours", "codecs": "LDAC, AAC, SBC", "color": "Black"},
        "images": ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-BOT-AIRDOPES-141",
        "name": "boAt Airdopes 141 ANC True Wireless Earbuds (Gunmetal Black)",
        "slug": "boat-airdopes-141-anc-black",
        "category": "audio-wearables",
        "brand": "boat",
        "seller": "soundwave",
        "price": 1799.0, "compare": 4490.0, "stock": 250, "rating": 4.4, "reviews": 315, "sales": 1140, "featured": False,
        "desc": "Up to 42 hours total playback, active noise cancellation up to 32dB, Beast Mode for 50ms low latency gaming, and ENx quad mics for crystal clear calls.",
        "attr": {"playback": "42 Hours with Case", "anc": "32dB Active Noise Cancellation", "latency": "50ms Beast Mode", "waterproof": "IPX5"},
        "images": ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-APL-AIRPODS-PRO-2",
        "name": "Apple AirPods Pro (2nd Generation) with MagSafe Case (USB-C)",
        "slug": "apple-airpods-pro-2nd-gen-usbc",
        "category": "audio-wearables",
        "brand": "apple",
        "seller": "techvault",
        "price": 24900.0, "compare": 24900.0, "stock": 70, "rating": 4.9, "reviews": 210, "sales": 580, "featured": True,
        "desc": "Engineered with the H2 chip. Up to 2x more active noise cancellation, Adaptive Audio, Personalized Spatial Audio with dynamic head tracking, and USB-C case.",
        "attr": {"chip": "Apple H2", "features": "Adaptive Audio, Transparency Mode, Spatial Audio", "case": "MagSafe USB-C with Speaker"},
        "images": ["https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-JBL-TUNE-770NC-BLU",
        "name": "JBL Tune 770NC Wireless Over-Ear Adaptive Noise Cancelling Headphones (Blue)",
        "slug": "jbl-tune-770nc-wireless-blue",
        "category": "audio-wearables",
        "brand": "jbl",
        "seller": "soundwave",
        "price": 5999.0, "compare": 9999.0, "stock": 90, "rating": 4.6, "reviews": 110, "sales": 390, "featured": False,
        "desc": "JBL Pure Bass Sound with Adaptive Noise Cancelling and Smart Ambient. Up to 70 hours battery life, speed charge (5 mins = 3 hrs), and multi-point Bluetooth 5.3.",
        "attr": {"battery": "Up to 70 Hours", "bluetooth": "5.3 Multi-Point", "sound": "JBL Pure Bass", "color": "Blue"},
        "images": ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-SNY-WF1000XM5-SLV",
        "name": "Sony WF-1000XM5 Wireless Noise Cancelling Earbuds (Silver)",
        "slug": "sony-wf-1000xm5-earbuds-silver",
        "category": "audio-wearables",
        "brand": "sony",
        "seller": "audioplanet",
        "price": 24990.0, "compare": 29990.0, "stock": 45, "rating": 4.8, "reviews": 85, "sales": 230, "featured": True,
        "desc": "Dynamic Driver X for wide frequency reproduction and deep bass, Integrated Processor V2 with HD Noise Cancelling Processor QN2e, bone conduction sensors for calls.",
        "attr": {"drivers": "Dynamic Driver X 8.4mm", "anc": "Dual Feedback Processors", "battery": "24h Total with Qi Wireless Case"},
        "images": ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-ONEP-BUDS-PRO-2",
        "name": "OnePlus Buds Pro 2 with Dynaudio MelodyBoost Dual Drivers (Obsidian Black)",
        "slug": "oneplus-buds-pro-2-obsidian-black",
        "category": "audio-wearables",
        "brand": "oneplus",
        "seller": "soundwave",
        "price": 9999.0, "compare": 13999.0, "stock": 65, "rating": 4.7, "reviews": 125, "sales": 370, "featured": False,
        "desc": "Co-created with Dynaudio featuring dual 11mm + 6mm drivers, up to 48dB Smart Adaptive Noise Cancellation, LHDC 4.0 Hi-Res audio, and 39 hours battery.",
        "attr": {"drivers": "11mm Woofer + 6mm Tweeter Dual Drivers", "anc": "48dB Smart Adaptive", "audio": "LHDC 4.0 Hi-Res"},
        "images": ["https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-RLM-BUDS-AIR-5-PRO",
        "name": "Realme Buds Air 5 Pro with 50dB Active Noise Cancellation (Sunrise Beige)",
        "slug": "realme-buds-air-5-pro-sunrise-beige",
        "category": "audio-wearables",
        "brand": "realme",
        "seller": "smartbuystore",
        "price": 4499.0, "compare": 7999.0, "stock": 110, "rating": 4.6, "reviews": 160, "sales": 540, "featured": False,
        "desc": "Sublime 50dB deep noise cancellation with 4000Hz ultra-wideband noise reduction, coaxial dual drivers, LDAC certified Hi-Res audio, and 40ms low latency.",
        "attr": {"anc": "50dB Deep Noise Cancellation", "codecs": "LDAC Hi-Res Audio", "latency": "40ms Game Mode"},
        "images": ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-JBL-FLIP-6-BLK",
        "name": "JBL Flip 6 Portable Waterproof Bluetooth Speaker (Powerful Sound, Black)",
        "slug": "jbl-flip-6-portable-speaker-black",
        "category": "audio-wearables",
        "brand": "jbl",
        "seller": "audioplanet",
        "price": 9999.0, "compare": 13999.0, "stock": 80, "rating": 4.8, "reviews": 210, "sales": 690, "featured": True,
        "desc": "Bold 2-way speaker system delivering loud, crystal clear, powerful audio. IP67 waterproof and dustproof with 12 hours of non-stop playtime and PartyBoost pairing.",
        "attr": {"waterproof": "IP67 Waterproof & Dustproof", "battery": "12 Hours Playtime", "features": "JBL PartyBoost Multi-Speaker Link"},
        "images": ["https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-SNY-SRS-XB100-BLU",
        "name": "Sony SRS-XB100 Wireless Ultra-Portable Bluetooth Speaker (Blue)",
        "slug": "sony-srs-xb100-wireless-speaker-blue",
        "category": "audio-wearables",
        "brand": "sony",
        "seller": "soundwave",
        "price": 3990.0, "compare": 4990.0, "stock": 95, "rating": 4.6, "reviews": 95, "sales": 380, "featured": False,
        "desc": "Compact body with mighty sound. Sound Diffusion Processor expands sound in any space, passive radiator boosts punchy bass, 16-hour battery, and multiway strap.",
        "attr": {"battery": "16 Hours", "rating": "IP67 Water and Dustproof", "strap": "Versatile Multiway Strap"},
        "images": ["https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-BOT-ROCKERZ-255-PRO",
        "name": "boAt Rockerz 255 Pro+ Bluetooth in-Ear Neckband (Active Black)",
        "slug": "boat-rockerz-255-pro-plus-neckband",
        "category": "audio-wearables",
        "brand": "boat",
        "seller": "soundwave",
        "price": 1299.0, "compare": 3990.0, "stock": 220, "rating": 4.5, "reviews": 420, "sales": 1600, "featured": False,
        "desc": "Massive 40 hours playback, ASAP fast charge (10 mins = 10 hrs), 10mm dynamic drivers, magnetic magnetic ear tips, IPX7 water & sweat resistance.",
        "attr": {"battery": "40 Hours Playback", "fast_charge": "ASAP Charge 10min = 10hr", "rating": "IPX7 Water Resistance"},
        "images": ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-ONEP-BULLETS-Z2",
        "name": "OnePlus Bullets Wireless Z2 Bluetooth Neckband with Bombastic Bass (Magico Black)",
        "slug": "oneplus-bullets-wireless-z2-black",
        "category": "audio-wearables",
        "brand": "oneplus",
        "seller": "smartbuystore",
        "price": 1799.0, "compare": 2299.0, "stock": 190, "rating": 4.6, "reviews": 310, "sales": 1290, "featured": False,
        "desc": "12.4mm mega bass driver, 30 hours playback on a single charge, 10-minute charge gives 20 hours audio, anti-distortion audio technology, and IP55 water resistance.",
        "attr": {"driver": "12.4mm Dynamic Bass", "battery": "30 Hours Battery Life", "rating": "IP55 Sweat & Water Resistant"},
        "images": ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-BOT-STONE-352-SPK",
        "name": "boAt Stone 352 10W Portable Wireless Speaker (Raging Black)",
        "slug": "boat-stone-352-10w-speaker-black",
        "category": "audio-wearables",
        "brand": "boat",
        "seller": "soundwave",
        "price": 1499.0, "compare": 3490.0, "stock": 180, "rating": 4.4, "reviews": 230, "sales": 880, "featured": False,
        "desc": "10W RMS immersive stereo sound, 12 hours playtime, IPX7 splash resistance, TWS technology to pair two Stone speakers for double the punch.",
        "attr": {"output": "10W RMS Stereo", "battery": "12 Hours", "durability": "IPX7 Water Resistant"},
        "images": ["https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "WEA-APL-WATCH-S9-45",
        "name": "Apple Watch Series 9 GPS 45mm (Midnight Aluminum, Midnight Sport Band)",
        "slug": "apple-watch-series-9-gps-45mm-midnight",
        "category": "audio-wearables",
        "brand": "apple",
        "seller": "techvault",
        "price": 44900.0, "compare": 44900.0, "stock": 35, "rating": 4.9, "reviews": 95, "sales": 260, "featured": True,
        "desc": "Powered by the S9 SiP chip with magical Double Tap gesture control, 2000 nits Always-On Retina display, advanced ECG, blood oxygen, and crash detection sensors.",
        "attr": {"size": "45mm", "chip": "Apple S9 SiP", "sensors": "ECG, Blood Oxygen, Temperature, Heart Rate", "display": "2000 nits Always-On Retina"},
        "images": ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "WEA-SAM-GALAXY-WATCH6",
        "name": "Samsung Galaxy Watch6 Bluetooth 44mm (Graphite Aluminum)",
        "slug": "samsung-galaxy-watch6-44mm-graphite",
        "category": "audio-wearables",
        "brand": "samsung",
        "seller": "primegadgets",
        "price": 28999.0, "compare": 33999.0, "stock": 40, "rating": 4.7, "reviews": 72, "sales": 190, "featured": False,
        "desc": "20% larger display with thinner bezel, advanced sleep coaching, BioActive Sensor for body composition analysis (BIA), heart health monitoring, and Wear OS powered by Samsung.",
        "attr": {"size": "44mm Sapphire Crystal", "sensors": "BioActive Sensor (ECG, BIA, Optical HR)", "battery": "Up to 40 hours", "os": "Wear OS 4"},
        "images": ["https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "WEA-NOI-COLORFIT-PRO5",
        "name": "Noise ColorFit Pro 5 Smartwatch with 1.85-inch AMOLED Display (Jet Black)",
        "slug": "noise-colorfit-pro-5-amoled-black",
        "category": "audio-wearables",
        "brand": "noise",
        "seller": "smartbuystore",
        "price": 3999.0, "compare": 8999.0, "stock": 130, "rating": 4.5, "reviews": 185, "sales": 670, "featured": False,
        "desc": "Postcard AMOLED display with 600 nits brightness, TruSync Bluetooth calling, functional digital crown, 100+ sports modes, and 7-day battery life.",
        "attr": {"display": "1.85 inch AMOLED (600 nits)", "calling": "TruSync Bluetooth Calling", "battery": "7 Days", "sensors": "SpO2, 24/7 Heart Rate"},
        "images": ["https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "WEA-BOT-WAVE-CALL-2",
        "name": "boAt Wave Call 2 Smartwatch with 1.83-inch HD Screen & BT Calling (Active Black)",
        "slug": "boat-wave-call-2-smartwatch",
        "category": "audio-wearables",
        "brand": "boat",
        "seller": "smartbuystore",
        "price": 1499.0, "compare": 6990.0, "stock": 240, "rating": 4.4, "reviews": 290, "sales": 1350, "featured": False,
        "desc": "1.83-inch HD display with 550 nits brightness, advanced Bluetooth calling with dialpad, 700+ active sports modes via Crest App, and IP67 water resistance.",
        "attr": {"screen": "1.83 inch HD (550 nits)", "features": "Bluetooth Calling with Dialpad", "tracking": "700+ Active Modes"},
        "images": ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "WEA-NOI-PULSE-2-MAX",
        "name": "Noise Pulse 2 Max 1.85-inch Display Bluetooth Calling Smartwatch (Deep Wine)",
        "slug": "noise-pulse-2-max-deep-wine",
        "category": "audio-wearables",
        "brand": "noise",
        "seller": "smartbuystore",
        "price": 1399.0, "compare": 5999.0, "stock": 170, "rating": 4.4, "reviews": 210, "sales": 890, "featured": False,
        "desc": "TFT LCD display with 550 nits peak brightness, 10-day battery backup, Smart DND mode, Noise Health Suite with blood oxygen and stress monitor.",
        "attr": {"screen": "1.85 inch TFT LCD", "battery": "10 Days", "calling": "BT Calling with 150+ Watch Faces"},
        "images": ["https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-JBL-GO-3-RED",
        "name": "JBL Go 3 Ultra-Portable Waterproof & Dustproof Bluetooth Speaker (Squad Red)",
        "slug": "jbl-go-3-portable-speaker-red",
        "category": "audio-wearables",
        "brand": "jbl",
        "seller": "audioplanet",
        "price": 2999.0, "compare": 3999.0, "stock": 140, "rating": 4.7, "reviews": 280, "sales": 980, "featured": False,
        "desc": "JBL Pro Sound in an ultra-compact pocket silhouette. Bold styling, edgy colorful fabrics, IP67 waterproof and dustproof rating, and 5 hours playtime.",
        "attr": {"sound": "JBL Pro Sound (4.2W)", "waterproof": "IP67 Certified", "portability": "Integrated Carabiner Loop"},
        "images": ["https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-BOT-BASSHEADS-100",
        "name": "boAt BassHeads 100 in-Ear Wired Earphones with Mic (Black)",
        "slug": "boat-bassheads-100-wired-earphones",
        "category": "audio-wearables",
        "brand": "boat",
        "seller": "smartbuystore",
        "price": 399.0, "compare": 999.0, "stock": 350, "rating": 4.3, "reviews": 540, "sales": 2400, "featured": False,
        "desc": "Hawk-inspired eye-catching earbud design with 10mm dynamic drivers, super extra bass, in-line microphone with answer/end button, and 1.2m tangle-free cable.",
        "attr": {"jack": "3.5mm Gold Plated", "driver": "10mm Dynamic Extra Bass", "mic": "In-line Clear Microphone"},
        "images": ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-SNY-MDR-ZX110",
        "name": "Sony MDR-ZX110 Wired On-Ear Headphones with 30mm Dynamic Drivers (Black)",
        "slug": "sony-mdr-zx110-wired-headphones",
        "category": "audio-wearables",
        "brand": "sony",
        "seller": "audioplanet",
        "price": 999.0, "compare": 1490.0, "stock": 160, "rating": 4.5, "reviews": 310, "sales": 1100, "featured": False,
        "desc": "30mm dome drivers deliver balanced sound across wide 12Hz-22kHz frequency range. Swivel folding design for effortless commute portability and cushioned earpads.",
        "attr": {"driver": "30mm Dome Drivers", "frequency": "12Hz - 22,000Hz", "folding": "Swivel Folding Earcups"},
        "images": ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-JBL-C100SI-RED",
        "name": "JBL C100SI Wired in-Ear Headphones with One-Button Universal Mic (Red)",
        "slug": "jbl-c100si-wired-headphones-red",
        "category": "audio-wearables",
        "brand": "jbl",
        "seller": "audioplanet",
        "price": 599.0, "compare": 1299.0, "stock": 280, "rating": 4.4, "reviews": 460, "sales": 1950, "featured": False,
        "desc": "Legendary JBL sound with powerful deep bass, featherweight ergonomic angled housing for hours of fatigue-free listening, and one-button universal remote.",
        "attr": {"connector": "3.5mm Jack", "bass": "JBL Signature Deep Bass", "weight": "Ultra-lightweight Ergonomic"},
        "images": ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "WEA-APL-WATCH-SE-40",
        "name": "Apple Watch SE (2nd Gen) GPS 40mm (Starlight Aluminum Case)",
        "slug": "apple-watch-se-2nd-gen-40mm-starlight",
        "category": "audio-wearables",
        "brand": "apple",
        "seller": "techvault",
        "price": 29900.0, "compare": 29900.0, "stock": 50, "rating": 4.8, "reviews": 115, "sales": 390, "featured": False,
        "desc": "All the essentials to help you stay motivated, active, connected, and safe. Enhanced workout app metrics, sleep stages tracking, Crash Detection, and water resistance 50m.",
        "attr": {"case_size": "40mm", "sensors": "Heart Rate, Accelerometer, Gyroscope", "water_resistance": "50m Swimproof"},
        "images": ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-BOT-PARTYPAL-50",
        "name": "boAt PartyPal 50 20W Wireless Party Speaker with RGB Flame LEDs",
        "slug": "boat-partypal-50-party-speaker",
        "category": "audio-wearables",
        "brand": "boat",
        "seller": "soundwave",
        "price": 2999.0, "compare": 6990.0, "stock": 75, "rating": 4.5, "reviews": 85, "sales": 290, "featured": False,
        "desc": "Pump up the celebration with 20W stereo output, multi-color dynamic flame RGB lights, mic input for karaoke singing, and 4.5 hours of continuous party playback.",
        "attr": {"output": "20W RMS", "lights": "Dynamic Flame RGB LEDs", "karaoke": "Dedicated Microphone Input"},
        "images": ["https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-SNY-CH520-WHT",
        "name": "Sony WH-CH520 Wireless Bluetooth On-Ear Headphones (50hr Battery, White)",
        "slug": "sony-wh-ch520-wireless-white",
        "category": "audio-wearables",
        "brand": "sony",
        "seller": "audioplanet",
        "price": 4490.0, "compare": 5990.0, "stock": 105, "rating": 4.7, "reviews": 140, "sales": 490, "featured": False,
        "desc": "Up to 50 hours of battery life and quick charging (3 mins = 1.5 hrs). Digital Sound Enhancement Engine (DSEE) restores lost harmonics in compressed audio.",
        "attr": {"battery": "50 Hours Battery", "enhancement": "Sony DSEE Sound Engine", "calling": "Hands-free Crystal Mic"},
        "images": ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "AUD-BOT-AVANTE-BAR-1160",
        "name": "boAt Aavante Bar 1160 60W 2.0 Channel Bluetooth Soundbar (Premium Black)",
        "slug": "boat-aavante-bar-1160-soundbar",
        "category": "audio-wearables",
        "brand": "boat",
        "seller": "soundwave",
        "price": 3999.0, "compare": 9990.0, "stock": 60, "rating": 4.5, "reviews": 160, "sales": 510, "featured": False,
        "desc": "Cinematic home entertainment with 60W RMS signature sound, dual 2.25-inch high-clarity drivers, EQ modes for movies/music/news, and multi-port connectivity.",
        "attr": {"output": "60W RMS", "channels": "2.0 Channel", "inputs": "Bluetooth v4.2, AUX, USB, Optical"},
        "images": ["https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "WEA-NOI-BUDS-VS104",
        "name": "Noise Buds VS104 Truly Wireless Earbuds with 45 Hours Playtime (Mint Green)",
        "slug": "noise-buds-vs104-mint-green",
        "category": "audio-wearables",
        "brand": "noise",
        "seller": "smartbuystore",
        "price": 1199.0, "compare": 3499.0, "stock": 210, "rating": 4.4, "reviews": 230, "sales": 920, "featured": False,
        "desc": "Instacharge (10 mins = 200 mins play), 13mm speaker driver for deep bass, Quad Mics with Environmental Noise Cancellation for phone calls, and IPX5 resistance.",
        "attr": {"playtime": "45 Hours Total", "driver": "13mm Titanium Coated", "charging": "Instacharge 10min = 200min"},
        "images": ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop"]
    },

    # =========================================================================
    # 4. FOOTWEAR & RUNNING (26 Products)
    # =========================================================================
    {
        "sku": "SHO-NIK-PEGASUS-40",
        "name": "Nike Air Zoom Pegasus 40 Men's Road Running Shoes (Black / White)",
        "slug": "nike-air-zoom-pegasus-40-black",
        "category": "footwear-running",
        "brand": "nike",
        "seller": "urbanfit",
        "price": 8995.0, "compare": 10495.0, "stock": 70, "rating": 4.8, "reviews": 98, "sales": 390, "featured": True,
        "desc": "A springy ride for every run. React foam technology coupled with two dual Zoom Air units delivers energized responsiveness and breathability across all distances.",
        "attr": {"surface": "Road Running", "cushioning": "Medium React Foam + Zoom Air", "drop": "10mm", "color": "Black / White", "size": "UK 9"},
        "images": ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-ADI-ULTRABOOST-LIGHT",
        "name": "Adidas Ultraboost Light Running Shoes (Core Black / Cloud White)",
        "slug": "adidas-ultraboost-light-core-black",
        "category": "footwear-running",
        "brand": "adidas",
        "seller": "urbanfit",
        "price": 14999.0, "compare": 18999.0, "stock": 50, "rating": 4.7, "reviews": 75, "sales": 260, "featured": True,
        "desc": "Experience epic energy return with the lightest Boost ever made. Continental rubber outsole provides extraordinary traction in wet and dry running conditions.",
        "attr": {"midsole": "Ultraboost Light (30% Lighter)", "upper": "Primeknit+ Textile", "outsole": "Continental Natural Rubber", "size": "UK 8"},
        "images": ["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-PUM-VELOCITY-NITRO-2",
        "name": "Puma Velocity Nitro 2 Lightweight Running Shoes (Royal Blue / Silver)",
        "slug": "puma-velocity-nitro-2-blue",
        "category": "footwear-running",
        "brand": "puma",
        "seller": "urbanfit",
        "price": 4999.0, "compare": 7999.0, "stock": 80, "rating": 4.6, "reviews": 62, "sales": 210, "featured": False,
        "desc": "An all-in-one neutral running shoe for any distance. Nitro foam cushioning delivers superior responsiveness in an exceptionally lightweight durable package.",
        "attr": {"foam": "NITRO FOAM Gas-Infused", "traction": "PUMAGRIP Rubber Compound", "weight": "257 grams", "size": "UK 9"},
        "images": ["https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-ASI-GEL-KAYANO-30",
        "name": "Asics GEL-Kayano 30 Stability Running Shoes (French Blue / Pure Silver)",
        "slug": "asics-gel-kayano-30-french-blue",
        "category": "footwear-running",
        "brand": "asics",
        "seller": "fitzone",
        "price": 12999.0, "compare": 15999.0, "stock": 45, "rating": 4.9, "reviews": 84, "sales": 290, "featured": True,
        "desc": "PureGEL technology cushioning paired with the revolutionary 4D GUIDANCE SYSTEM provides adaptive stability for overpronation on long distance marathon runs.",
        "attr": {"technology": "PureGEL + 4D Guidance System", "support": "Maximum Stability / Overpronation", "surface": "Road / Pavement", "size": "UK 8.5"},
        "images": ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-NIK-INFINITYRN-4",
        "name": "Nike InfinityRN 4 Men's Supportive Road Running Shoes (Platinum Tint)",
        "slug": "nike-infinityrn-4-platinum-tint",
        "category": "footwear-running",
        "brand": "nike",
        "seller": "urbanfit",
        "price": 11995.0, "compare": 14995.0, "stock": 55, "rating": 4.7, "reviews": 56, "sales": 180, "featured": False,
        "desc": "Engineered with all-new Nike ReactX foam delivering 13% more energy return compared to React foam, with Flyknit collar and rocker-shaped sole for smooth strides.",
        "attr": {"foam": "Nike ReactX High-Rebound", "upper": "Flyknit Breathable Sock-like", "stack": "Rocker Geometry"},
        "images": ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-ADI-ADIZERO-BOSTON12",
        "name": "Adidas Adizero Boston 12 Marathon Training Running Shoes (Solar Red)",
        "slug": "adidas-adizero-boston-12-solar-red",
        "category": "footwear-running",
        "brand": "adidas",
        "seller": "fitzone",
        "price": 12799.0, "compare": 15999.0, "stock": 40, "rating": 4.8, "reviews": 68, "sales": 220, "featured": False,
        "desc": "Built for fast tempo training days with glass-fiber ENERGYRODS 2.0 underfoot for snappy propulsion, combining Lightstrike Pro and Lightstrike 2.0 foam layers.",
        "attr": {"rods": "ENERGYRODS 2.0 Glass-Fiber", "midsole": "Lightstrike Pro + Lightstrike 2.0", "weight": "260 grams"},
        "images": ["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-ASI-NOVABLAST-4",
        "name": "Asics Novablast 4 High-Energy Return Running Shoes (Illusion Blue)",
        "slug": "asics-novablast-4-illusion-blue",
        "category": "footwear-running",
        "brand": "asics",
        "seller": "fitzone",
        "price": 11999.0, "compare": 13999.0, "stock": 50, "rating": 4.8, "reviews": 72, "sales": 270, "featured": False,
        "desc": "Trampoline-inspired outsole geometry with FF BLAST PLUS ECO cushioning manufactured with 20% recycled bio-based content for explosive toe-offs.",
        "attr": {"cushioning": "FF BLAST PLUS ECO", "outsole": "AHAR Low-Hardness Rubber", "drop": "8mm"},
        "images": ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-PUM-DEVIATE-NITRO-2",
        "name": "Puma Deviate Nitro 2 Carbon-Plated Running Shoes (Fireglow Orange)",
        "slug": "puma-deviate-nitro-2-fireglow",
        "category": "footwear-running",
        "brand": "puma",
        "seller": "fitzone",
        "price": 9999.0, "compare": 15999.0, "stock": 35, "rating": 4.8, "reviews": 48, "sales": 150, "featured": True,
        "desc": "Full-length INNOPLATE carbon composite plate acts as a lever for maximum propulsion, wrapped in nitrogen-infused NITRO Elite foam for race day speed.",
        "attr": {"plate": "INNOPLATE Carbon Composite", "foam": "NITRO Elite High-Rebound", "weight": "250g"},
        "images": ["https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-UA-HOVR-SONIC-6",
        "name": "Under Armour HOVR Sonic 6 Running Shoes (Pitch Gray / White)",
        "slug": "under-armour-hovr-sonic-6-pitch-gray",
        "category": "footwear-running",
        "brand": "under-armour",
        "seller": "urbanfit",
        "price": 6999.0, "compare": 9999.0, "stock": 65, "rating": 4.6, "reviews": 52, "sales": 190, "featured": False,
        "desc": "Zero-gravity feel with UA HOVR cushioning that maintains energy return, engineered mesh upper with seamless forefoot for breathable comfort.",
        "attr": {"cushioning": "UA HOVR Zero Gravity", "upper": "Engineered Spacer Mesh", "outsole": "High-Abrasion Carbon Rubber"},
        "images": ["https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-NIK-REVOLUTION-7",
        "name": "Nike Revolution 7 Men's Road Running Shoes (Obsidian Blue)",
        "slug": "nike-revolution-7-obsidian-blue",
        "category": "footwear-running",
        "brand": "nike",
        "seller": "urbanfit",
        "price": 3695.0, "compare": 4295.0, "stock": 120, "rating": 4.5, "reviews": 160, "sales": 640, "featured": False,
        "desc": "Soft foam midsole cushions your steps, generative traction pattern outsole grips hills and sidewalks, touchpoints at heel and tongue create natural ease.",
        "attr": {"type": "Everyday Beginner Running", "cushioning": "Soft Foam", "upper": "Breathable Knit"},
        "images": ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-ADI-DURAMO-SPEED",
        "name": "Adidas Duramo Speed Running Shoes (Core Black / Silver Metallic)",
        "slug": "adidas-duramo-speed-black-silver",
        "category": "footwear-running",
        "brand": "adidas",
        "seller": "urbanfit",
        "price": 4299.0, "compare": 6999.0, "stock": 100, "rating": 4.5, "reviews": 130, "sales": 520, "featured": False,
        "desc": "Lightstrike cushioning provides lightweight speed without sacrificing longevity, engineered mesh upper keeps feet ventilated during morning 5K runs.",
        "attr": {"midsole": "Lightstrike Cushioning", "outsole": "Adiwear Long-Lasting Rubber", "weight": "270g"},
        "images": ["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-PUM-TRANSPORT-RUN",
        "name": "Puma Transport Men's Daily Walking & Running Shoes (Castlerock)",
        "slug": "puma-transport-running-shoes-castlerock",
        "category": "footwear-running",
        "brand": "puma",
        "seller": "urbanfit",
        "price": 2499.0, "compare": 3999.0, "stock": 140, "rating": 4.4, "reviews": 180, "sales": 780, "featured": False,
        "desc": "Structured support for daily jogging, treadmill walking, and casual errands with clean aesthetic lines, padded collar, and EVA midsole cushioning.",
        "attr": {"use": "Daily Jogging & Walking", "midsole": "Cushioned EVA", "upper": "Textile Mesh with Synthetic Overlays"},
        "images": ["https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-ASI-GEL-NIMBUS-26",
        "name": "Asics GEL-Nimbus 26 Maximum Cushioning Running Shoes (Black / Graphite)",
        "slug": "asics-gel-nimbus-26-black-graphite",
        "category": "footwear-running",
        "brand": "asics",
        "seller": "fitzone",
        "price": 14999.0, "compare": 17999.0, "stock": 40, "rating": 4.9, "reviews": 88, "sales": 310, "featured": True,
        "desc": "Cloud-like plush comfort for recovery miles. Combines FF BLAST PLUS ECO foam with soft PureGEL technology in the heel, and ASICSGRIP hybrid traction outsole.",
        "attr": {"category": "Max Cushion Neutral", "cushioning": "FF BLAST PLUS ECO + PureGEL", "upper": "Engineered Knit"},
        "images": ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-NIK-AIR-MAX-270",
        "name": "Nike Air Max 270 Men's Lifestyle & Walking Shoes (Triple Black)",
        "slug": "nike-air-max-270-triple-black",
        "category": "footwear-running",
        "brand": "nike",
        "seller": "urbanfit",
        "price": 12995.0, "compare": 13995.0, "stock": 65, "rating": 4.8, "reviews": 145, "sales": 480, "featured": False,
        "desc": "Nike's biggest heel Air unit yet delivers ultra-soft cushioning that feels as impossible as it looks, with stretchy inner bootie construction for personalized fit.",
        "attr": {"air_unit": "Large 270-Degree Visible Max Air", "upper": "Woven and Synthetic Fabric", "style": "Sportswear / Walking"},
        "images": ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-ADI-STAN-SMITH",
        "name": "Adidas Originals Stan Smith Classic Leather Sneakers (White / Green)",
        "slug": "adidas-originals-stan-smith-white-green",
        "category": "footwear-running",
        "brand": "adidas",
        "seller": "stylemart",
        "price": 6799.0, "compare": 8999.0, "stock": 85, "rating": 4.7, "reviews": 210, "sales": 720, "featured": False,
        "desc": "Timeless tennis court silhouette with perforated 3-Stripes, iconic green heel tab, soft synthetic leather upper made with Primegreen high-performance recycled materials.",
        "attr": {"material": "Primegreen Vegan Leather", "sole": "Ortholite Sockliner + Rubber Cupsole", "style": "Retro Casual Sneaker"},
        "images": ["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-PUM-SUEDE-CLASSIC",
        "name": "Puma Suede Classic XXI Heritage Sneakers (Peacoat Navy / White)",
        "slug": "puma-suede-classic-xxi-navy",
        "category": "footwear-running",
        "brand": "puma",
        "seller": "stylemart",
        "price": 4499.0, "compare": 6999.0, "stock": 95, "rating": 4.6, "reviews": 175, "sales": 580, "featured": False,
        "desc": "Born in 1968, worn by icons of every generation. Features full premium velvety suede upper, comfortable comfort sockliner, and classic textured rubber midsole.",
        "attr": {"upper": "100% Genuine Suede", "outsole": "Non-Marking Textured Rubber", "style": "Streetwear Heritage"},
        "images": ["https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-NIK-METCON-9",
        "name": "Nike Metcon 9 Men's Cross-Training & Weightlifting Shoes (Smoke Grey)",
        "slug": "nike-metcon-9-cross-training",
        "category": "footwear-running",
        "brand": "nike",
        "seller": "fitzone",
        "price": 11895.0, "compare": 13995.0, "stock": 45, "rating": 4.9, "reviews": 64, "sales": 230, "featured": True,
        "desc": "The gold standard for lifting and CrossFit. Larger Hyperlift plate in the heel provides stability for tough workouts like split squats and deadlifts.",
        "attr": {"discipline": "CrossFit / Heavy Lifting / HIIT", "heel": "Enlarged Hyperlift Stability Plate", "durability": "Rope Wrap Grip"},
        "images": ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-UA-CHARGED-ASSERT-10",
        "name": "Under Armour Charged Assert 10 Running Shoes (Black / Metallic)",
        "slug": "under-armour-charged-assert-10-black",
        "category": "footwear-running",
        "brand": "under-armour",
        "seller": "urbanfit",
        "price": 4499.0, "compare": 6499.0, "stock": 90, "rating": 4.6, "reviews": 110, "sales": 410, "featured": False,
        "desc": "Charged Cushioning compression molded foam protects against impact while leather overlays lock in midfoot stability on street and track.",
        "attr": {"midsole": "Charged Cushioning", "overlays": "Durable Leather Midfoot Lock", "insole": "EVA Sockliner"},
        "images": ["https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-ASI-GT2000-12",
        "name": "Asics GT-2000 12 Moderate Stability Road Running Shoes (Black / White)",
        "slug": "asics-gt-2000-12-running-shoes",
        "category": "footwear-running",
        "brand": "asics",
        "seller": "fitzone",
        "price": 10999.0, "compare": 12999.0, "stock": 55, "rating": 4.8, "reviews": 70, "sales": 240, "featured": False,
        "desc": "3D GUIDANCE SYSTEM offers on-demand stability to guide your stride smoothly, combined with PureGEL heel cushioning and FF BLAST PLUS foam.",
        "attr": {"stability": "3D Guidance System", "foam": "FF BLAST PLUS", "drop": "8mm"},
        "images": ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-ADI-TERREX-SOULSTRIDE",
        "name": "Adidas Terrex Soulstride Trail Running Shoes (Core Black / Impact Orange)",
        "slug": "adidas-terrex-soulstride-trail",
        "category": "footwear-running",
        "brand": "adidas",
        "seller": "fitzone",
        "price": 6999.0, "compare": 8999.0, "stock": 50, "rating": 4.7, "reviews": 55, "sales": 180, "featured": False,
        "desc": "Hybrid lugged Traxion outsole easily transitions from asphalt streets to rocky dirt trails. Thick EVA midsole cushions uneven rocky terrain.",
        "attr": {"terrain": "Trail & Hybrid Road-to-Trail", "outsole": "Traxion Lugged Rubber", "sidewall": "Raised Stability Flanges"},
        "images": ["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-NIK-DOWNSHIFTER-12",
        "name": "Nike Downshifter 12 Lightweight Road Running Shoes (Dark Smoke Grey)",
        "slug": "nike-downshifter-12-smoke-grey",
        "category": "footwear-running",
        "brand": "nike",
        "seller": "urbanfit",
        "price": 3295.0, "compare": 3995.0, "stock": 135, "rating": 4.4, "reviews": 190, "sales": 760, "featured": False,
        "desc": "Midfoot fitband gives you stability where you need it, super soft foam through the midsole cushions your foot with every step.",
        "attr": {"type": "Entry Level Running", "sustainability": "Made with at least 20% recycled content", "upper": "Lightweight Mesh"},
        "images": ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-PUM-SMASH-V2-L",
        "name": "Puma Smash v2 L Unisex Leather Tennis Sneakers (Puma White / Black)",
        "slug": "puma-smash-v2-leather-white",
        "category": "footwear-running",
        "brand": "puma",
        "seller": "stylemart",
        "price": 2799.0, "compare": 3999.0, "stock": 150, "rating": 4.5, "reviews": 240, "sales": 890, "featured": False,
        "desc": "Soft leather upper with improved fit, durable rubber outsole for great traction, and SoftFoam+ comfort sockliner for instant step-in cushioning.",
        "attr": {"material": "Soft Genuine Leather", "insole": "SoftFoam+ Optimal Comfort", "style": "Minimalist White Sneaker"},
        "images": ["https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-UA-TRIBASE-REIGN-5",
        "name": "Under Armour TriBase Reign 5 Gym Cross-Trainer Shoes (White / Mod Gray)",
        "slug": "under-armour-tribase-reign-5",
        "category": "footwear-running",
        "brand": "under-armour",
        "seller": "fitzone",
        "price": 8999.0, "compare": 11999.0, "stock": 40, "rating": 4.8, "reviews": 48, "sales": 160, "featured": False,
        "desc": "UA TriBase maximizes ground contact where your foot needs it most, allows superior upward flexibility, and downward flexibility to grip the floor during lifts.",
        "attr": {"technology": "UA TriBase Floor Contact", "midsole": "Micro G Foam", "upper": "Warp Upper Lock"},
        "images": ["https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-ASI-CONTEND-8",
        "name": "Asics Gel-Contend 8 Entry-Level Running Shoes (Carrier Grey / Safety Yellow)",
        "slug": "asics-gel-contend-8-carrier-grey",
        "category": "footwear-running",
        "brand": "asics",
        "seller": "urbanfit",
        "price": 3499.0, "compare": 4499.0, "stock": 110, "rating": 4.5, "reviews": 130, "sales": 490, "featured": False,
        "desc": "Rearfoot GEL technology absorbs shock during heel strike, AMPLIFOAM cushioning provides durable durability, and OrthoLite sockliner adds step-in comfort.",
        "attr": {"cushioning": "Rearfoot GEL + AMPLIFOAM", "insole": "OrthoLite", "toe": "Reinforced Toe Stitching"},
        "images": ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-NIK-AIR-MONARCH-IV",
        "name": "Nike Air Monarch IV Men's Durable Training Shoes (White / Metallic Silver)",
        "slug": "nike-air-monarch-iv-white-silver",
        "category": "footwear-running",
        "brand": "nike",
        "seller": "urbanfit",
        "price": 4995.0, "compare": 5495.0, "stock": 95, "rating": 4.6, "reviews": 210, "sales": 690, "featured": False,
        "desc": "Full-length encapsulated Air-Sole unit cushions every stride while durable leather upper gives structured support for gym lifting and all-day walking.",
        "attr": {"upper": "Genuine & Synthetic Leather", "cushioning": "Encapsulated Air-Sole", "width": "Comfortable Wide Fit"},
        "images": ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "SHO-ADI-GALAXY-6",
        "name": "Adidas Galaxy 6 Breathable Everyday Running Shoes (Cloud White / Core Black)",
        "slug": "adidas-galaxy-6-cloud-white",
        "category": "footwear-running",
        "brand": "adidas",
        "seller": "urbanfit",
        "price": 3199.0, "compare": 4999.0, "stock": 130, "rating": 4.4, "reviews": 165, "sales": 580, "featured": False,
        "desc": "Plush Cloudfoam midsole cushioning ensures you stay comfortable from morning sprints to evening grocery runs, with airy mesh upper to keep heat away.",
        "attr": {"midsole": "Cloudfoam Super Soft", "upper": "Ventilated Air Mesh", "outsole": "Rubber Grippy Outsole"},
        "images": ["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop"]
    }
]
