"""
Structured Product Catalog Dataset for AI E-Commerce Marketplace.
Contains 216 unique products across 9 core categories with authentic Indian Rupee (INR) pricing,
specifications, multi-vendor seller assignments, brand mapping, and Unsplash imagery.
"""

PRODUCTS_CATALOG = [
    # =========================================================================
    # 1. LAPTOPS & COMPUTING (26 Products)
    # =========================================================================
    {
        "sku": "LAP-APL-MBP-14-M3",
        "name": "Apple MacBook Pro 14 M3 Pro (18GB, 512GB SSD, Space Black)",
        "slug": "apple-macbook-pro-14-m3-space-black",
        "category": "laptops-computing",
        "brand": "apple",
        "seller": "techvault",
        "price": 199900.0, "compare": 219900.0, "stock": 45, "rating": 4.9, "reviews": 68, "sales": 140, "featured": True,
        "desc": "Engineered with the Apple M3 Pro chip featuring 11-core CPU and 14-core GPU. Liquid Retina XDR display with ProMotion 120Hz and 18-hour battery endurance.",
        "attr": {"processor": "Apple M3 Pro", "ram": "18GB Unified", "storage": "512GB SSD", "display": "14.2 inch Liquid Retina XDR", "color": "Space Black"},
        "images": ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "LAP-DEL-XPS-15-OLED",
        "name": "Dell XPS 15 9530 Core i7 (32GB, 1TB SSD, RTX 4060, Platinum Silver)",
        "slug": "dell-xps-15-oled-core-i7",
        "category": "laptops-computing",
        "brand": "dell",
        "seller": "techvault",
        "price": 174900.0, "compare": 189900.0, "stock": 30, "rating": 4.7, "reviews": 42, "sales": 95, "featured": True,
        "desc": "Stunning 3.5K OLED InfinityEdge touch display with Intel Core i7 13th Gen, 32GB DDR5 RAM, and NVIDIA GeForce RTX 4060 studio graphics.",
        "attr": {"processor": "Intel Core i7-13700H", "ram": "32GB DDR5", "storage": "1TB NVMe SSD", "display": "15.6 inch 3.5K OLED Touch", "gpu": "RTX 4060 8GB"},
        "images": ["https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "LAP-HP-SPEC-X360-14",
        "name": "HP Spectre x360 2-in-1 OLED Laptop (Core Ultra 7, 16GB, 1TB SSD)",
        "slug": "hp-spectre-x360-14-oled-ultra-7",
        "category": "laptops-computing",
        "brand": "hp",
        "seller": "digitalhub",
        "price": 159990.0, "compare": 174990.0, "stock": 25, "rating": 4.8, "reviews": 34, "sales": 80, "featured": True,
        "desc": "Ultra-versatile 2-in-1 convertible laptop powered by Intel Core Ultra 7 with built-in Intel AI Boost NPU, 2.8K 120Hz IMAX Enhanced OLED touch display, and stylus pen.",
        "attr": {"processor": "Intel Core Ultra 7 155H", "ram": "16GB LPDDR5x", "storage": "1TB SSD", "display": "14 inch 2.8K OLED Touch", "weight": "1.44 kg"},
        "images": ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "LAP-LEN-THINKPAD-X1",
        "name": "Lenovo ThinkPad X1 Carbon Gen 11 (Core i7, 16GB, 512GB SSD, Ultralight)",
        "slug": "lenovo-thinkpad-x1-carbon-gen-11",
        "category": "laptops-computing",
        "brand": "lenovo",
        "seller": "digitalhub",
        "price": 149990.0, "compare": 169990.0, "stock": 20, "rating": 4.8, "reviews": 29, "sales": 65, "featured": False,
        "desc": "Legendary enterprise ultrabook engineered with aerospace-grade carbon fiber chassis, legendary ThinkPad keyboard, Intel vPro Core i7, and Rapid Charge technology.",
        "attr": {"processor": "Intel Core i7-1355U vPro", "ram": "16GB LPDDR5", "storage": "512GB SSD", "display": "14 inch WUXGA Anti-Glare", "weight": "1.12 kg"},
        "images": ["https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "LAP-ASU-ZEPH-G16-4070",
        "name": "ASUS ROG Zephyrus G16 Gaming Laptop (Intel Core Ultra 9, 32GB, RTX 4070)",
        "slug": "asus-rog-zephyrus-g16-ultra-9-rtx4070",
        "category": "laptops-computing",
        "brand": "asus",
        "seller": "apexcomputex",
        "price": 209990.0, "compare": 229990.0, "stock": 15, "rating": 4.9, "reviews": 22, "sales": 55, "featured": True,
        "desc": "Ultra-thin aluminum unibody gaming powerhouse featuring 2.5K 240Hz ROG Nebula OLED display, NVIDIA GeForce RTX 4070 graphics, and advanced vapor chamber cooling.",
        "attr": {"processor": "Intel Core Ultra 9 185H", "ram": "32GB LPDDR5x", "storage": "1TB NVMe Gen4 SSD", "gpu": "NVIDIA RTX 4070 8GB", "display": "16 inch 240Hz OLED"},
        "images": ["https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "LAP-ACR-PRED-HEL-16",
        "name": "Acer Predator Helios 16 Gaming Laptop (13th Gen Core i9, 16GB, RTX 4080)",
        "slug": "acer-predator-helios-16-i9-rtx4080",
        "category": "laptops-computing",
        "brand": "acer",
        "seller": "apexcomputex",
        "price": 194990.0, "compare": 219990.0, "stock": 12, "rating": 4.7, "reviews": 18, "sales": 40, "featured": False,
        "desc": "Dominate AAA titles with desktop-grade 24-core Intel Core i9, full TGP NVIDIA GeForce RTX 4080 graphics, 240Hz WQXGA display, and liquid metal cooling.",
        "attr": {"processor": "Intel Core i9-13900HX", "ram": "16GB DDR5", "storage": "1TB SSD", "gpu": "RTX 4080 12GB (175W)", "display": "16 inch WQXGA 240Hz"},
        "images": ["https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "LAP-APL-MBA-13-M2",
        "name": "Apple MacBook Air 13 M2 (8GB RAM, 256GB SSD, Midnight)",
        "slug": "apple-macbook-air-13-m2-midnight",
        "category": "laptops-computing",
        "brand": "apple",
        "seller": "techvault",
        "price": 94990.0, "compare": 114900.0, "stock": 60, "rating": 4.8, "reviews": 92, "sales": 310, "featured": True,
        "desc": "Strikingly thin fanless design with M2 silicon chip, 13.6-inch Liquid Retina display, 1080p FaceTime HD camera, MagSafe 3 charging port, and all-day battery.",
        "attr": {"processor": "Apple M2 (8-core)", "ram": "8GB Unified", "storage": "256GB SSD", "display": "13.6 inch Liquid Retina", "color": "Midnight"},
        "images": ["https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "LAP-LEN-LEG-PRO-5",
        "name": "Lenovo Legion Pro 5 AMD Ryzen 7 (16GB, 1TB SSD, RTX 4060)",
        "slug": "lenovo-legion-pro-5-ryzen-7-rtx4060",
        "category": "laptops-computing",
        "brand": "lenovo",
        "seller": "apexcomputex",
        "price": 124990.0, "compare": 144990.0, "stock": 25, "rating": 4.7, "reviews": 38, "sales": 90, "featured": False,
        "desc": "Engineered for esports with AMD Ryzen 7 7745HX octa-core CPU, 165Hz WQXGA IPS screen with 100% sRGB, Legion Coldfront 5.0 thermal system, and RGB keyboard.",
        "attr": {"processor": "AMD Ryzen 7 7745HX", "ram": "16GB DDR5", "storage": "1TB SSD", "gpu": "RTX 4060 8GB", "display": "16 inch 165Hz WQXGA"},
        "images": ["https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "LAP-DEL-INSP-14-PLUS",
        "name": "Dell Inspiron 14 Plus Core i7 (16GB RAM, 1TB SSD, Dark Green)",
        "slug": "dell-inspiron-14-plus-core-i7",
        "category": "laptops-computing",
        "brand": "dell",
        "seller": "digitalhub",
        "price": 89990.0, "compare": 104990.0, "stock": 35, "rating": 4.6, "reviews": 45, "sales": 120, "featured": False,
        "desc": "Slim yet potent productivity laptop with Intel Core i7 H-series processor, 2.2K anti-glare display with ComfortView Plus, and aluminum chassis.",
        "attr": {"processor": "Intel Core i7-13700H", "ram": "16GB DDR5", "storage": "1TB NVMe", "display": "14 inch 2.2K (2240x1400)", "weight": "1.66 kg"},
        "images": ["https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "LAP-HP-PAV-15-I5",
        "name": "HP Pavilion 15 Core i5 13th Gen (16GB RAM, 512GB SSD, Natural Silver)",
        "slug": "hp-pavilion-15-core-i5-silver",
        "category": "laptops-computing",
        "brand": "hp",
        "seller": "smartbuystore",
        "price": 64990.0, "compare": 76990.0, "stock": 50, "rating": 4.5, "reviews": 60, "sales": 210, "featured": False,
        "desc": "Reliable daily computing workhorse with Intel Core i5 13th Gen, 15.6-inch Full HD micro-edge display, Audio by B&O, and HP Fast Charge support.",
        "attr": {"processor": "Intel Core i5-1335U", "ram": "16GB DDR4", "storage": "512GB SSD", "display": "15.6 inch FHD IPS", "audio": "B&O Dual Speakers"},
        "images": ["https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "LAP-ASU-ZEN-14-OLED",
        "name": "ASUS ZenBook 14 OLED Core Ultra 5 (16GB, 1TB SSD, Ponder Blue)",
        "slug": "asus-zenbook-14-oled-core-ultra-5",
        "category": "laptops-computing",
        "brand": "asus",
        "seller": "digitalhub",
        "price": 99990.0, "compare": 114990.0, "stock": 28, "rating": 4.7, "reviews": 31, "sales": 85, "featured": False,
        "desc": "Ultra-light 1.2kg chassis featuring Intel Core Ultra 5 with AI NPU acceleration, 3K 120Hz ASUS Lumina OLED display with 600 nits HDR, and 75Wh battery.",
        "attr": {"processor": "Intel Core Ultra 5 125H", "ram": "16GB LPDDR5x", "storage": "1TB SSD", "display": "14 inch 3K OLED 120Hz", "weight": "1.2 kg"},
        "images": ["https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "LAP-ACR-SWIFT-GO-14",
        "name": "Acer Swift Go 14 OLED Intel Core i5 (16GB, 512GB SSD, Pure Silver)",
        "slug": "acer-swift-go-14-oled-i5",
        "category": "laptops-computing",
        "brand": "acer",
        "seller": "smartbuystore",
        "price": 69990.0, "compare": 82990.0, "stock": 40, "rating": 4.6, "reviews": 48, "sales": 130, "featured": False,
        "desc": "Vibrant 2.8K 90Hz OLED display with 100% DCI-P3 color gamut, Intel Core i5 13th Gen H-series CPU, 1440p QHD webcam, and dual copper heat-pipe cooling.",
        "attr": {"processor": "Intel Core i5-13500H", "ram": "16GB LPDDR5", "storage": "512GB SSD", "display": "14 inch 2.8K OLED", "camera": "1440p QHD"},
        "images": ["https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "LAP-SAM-GB3-PRO-360",
        "name": "Samsung Galaxy Book3 Pro 360 2-in-1 (Core i7, 16GB, 1TB SSD, S-Pen)",
        "slug": "samsung-galaxy-book3-pro-360-i7",
        "category": "laptops-computing",
        "brand": "samsung",
        "seller": "techvault",
        "price": 169990.0, "compare": 184990.0, "stock": 18, "rating": 4.8, "reviews": 25, "sales": 70, "featured": False,
        "desc": "Transformable 360-degree convertible with 16-inch 3K Dynamic AMOLED 2X touch screen, included S Pen stylus, quad AKG speakers, and Galaxy ecosystem sync.",
        "attr": {"processor": "Intel Core i7-1360P", "ram": "16GB LPDDR5", "storage": "1TB SSD", "display": "16 inch 3K AMOLED Touch", "extras": "S-Pen Included"},
        "images": ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "LAP-DEL-ALIEN-M16",
        "name": "Dell Alienware m16 R2 Gaming Laptop (Core Ultra 7, 32GB, RTX 4070)",
        "slug": "dell-alienware-m16-r2-rtx4070",
        "category": "laptops-computing",
        "brand": "dell",
        "seller": "apexcomputex",
        "price": 219990.0, "compare": 249990.0, "stock": 8, "rating": 4.9, "reviews": 16, "sales": 35, "featured": True,
        "desc": "Iconic Alienware Legend 3 industrial design with Cryo-tech cooling, 240Hz QHD+ display, per-key AlienFX RGB keyboard, and Stealth Mode battery tuning.",
        "attr": {"processor": "Intel Core Ultra 7 155H", "ram": "32GB DDR5", "storage": "1TB SSD", "gpu": "RTX 4070 8GB", "display": "16 inch QHD+ 240Hz"},
        "images": ["https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-LOGI-MX-MASTER-3S",
        "name": "Logitech MX Master 3S Wireless Performance Mouse (Quiet Clicks, 8K DPI)",
        "slug": "logitech-mx-master-3s-graphite",
        "category": "laptops-computing",
        "brand": "logitech",
        "seller": "digitalhub",
        "price": 9495.0, "compare": 10995.0, "stock": 85, "rating": 4.9, "reviews": 180, "sales": 520, "featured": True,
        "desc": "Ergonomic master productivity mouse with MagSpeed electromagnetic scrolling, 8,000 DPI track-on-glass sensor, 90% quieter clicks, and multi-computer Flow control.",
        "attr": {"dpi": "8000 DPI", "connectivity": "Bluetooth / Logi Bolt", "battery": "70 days per charge", "color": "Graphite"},
        "images": ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-LOGI-MX-KEYS-MINI",
        "name": "Logitech MX Keys Mini Wireless Illuminated Keyboard (Pale Grey)",
        "slug": "logitech-mx-keys-mini-pale-grey",
        "category": "laptops-computing",
        "brand": "logitech",
        "seller": "digitalhub",
        "price": 8995.0, "compare": 10495.0, "stock": 65, "rating": 4.8, "reviews": 110, "sales": 340, "featured": False,
        "desc": "Minimalist tenkeyless layout with spherically-dished PerfectStroke keys, smart proximity backlighting, dictation key, and seamless multi-device Bluetooth switching.",
        "attr": {"layout": "Tenkeyless (Compact)", "backlight": "Smart Proximity White LED", "connectivity": "Bluetooth LE", "color": "Pale Grey"},
        "images": ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-SAN-EXT-SSD-1TB",
        "name": "SanDisk Extreme 1TB Portable External SSD (1050MB/s, IP65 Rugged)",
        "slug": "sandisk-extreme-1tb-portable-ssd",
        "category": "laptops-computing",
        "brand": "sandisk",
        "seller": "digitalhub",
        "price": 8999.0, "compare": 12999.0, "stock": 110, "rating": 4.8, "reviews": 215, "sales": 640, "featured": True,
        "desc": "Tough NVMe solid-state storage with up to 1050MB/s read speeds, 3-meter drop protection, IP65 water/dust resistance, and carabiner loop for outdoor travel.",
        "attr": {"capacity": "1TB", "speed": "Up to 1050MB/s", "durability": "IP65 Water & Dust Resistant", "interface": "USB 3.2 Gen 2 Type-C"},
        "images": ["https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-SAN-EXT-SSD-2TB",
        "name": "SanDisk Extreme 2TB High-Speed Portable NVMe SSD (Type-C)",
        "slug": "sandisk-extreme-2tb-portable-ssd",
        "category": "laptops-computing",
        "brand": "sandisk",
        "seller": "digitalhub",
        "price": 16499.0, "compare": 22999.0, "stock": 70, "rating": 4.8, "reviews": 95, "sales": 280, "featured": False,
        "desc": "Massive 2TB capacity with blazing NVMe performance for 4K video editing, RAW photo libraries, and critical system backups with 256-bit AES hardware encryption.",
        "attr": {"capacity": "2TB", "speed": "1050MB/s", "durability": "IP65 Rated", "interface": "USB-C"},
        "images": ["https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-DEL-U2723QE-MON",
        "name": "Dell UltraSharp 27 4K USB-C Hub Monitor (IPS Black, 98% DCI-P3)",
        "slug": "dell-ultrasharp-27-4k-u2723qe-monitor",
        "category": "laptops-computing",
        "brand": "dell",
        "seller": "digitalhub",
        "price": 56990.0, "compare": 67990.0, "stock": 22, "rating": 4.9, "reviews": 55, "sales": 115, "featured": True,
        "desc": "Professional creative monitor with groundbreaking IPS Black panel technology boasting 2000:1 contrast ratio, 90W USB-C power delivery, RJ45 Ethernet, and KVM switch.",
        "attr": {"size": "27 inch", "resolution": "4K UHD (3840x2160)", "panel": "IPS Black", "ports": "USB-C 90W, DisplayPort, HDMI, RJ45"},
        "images": ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-SAM-ODYSSEY-G7",
        "name": "Samsung Odyssey G7 28-inch 4K 144Hz Gaming Monitor (1ms, HDR400)",
        "slug": "samsung-odyssey-g7-28-4k-144hz",
        "category": "laptops-computing",
        "brand": "samsung",
        "seller": "apexcomputex",
        "price": 44990.0, "compare": 54990.0, "stock": 19, "rating": 4.7, "reviews": 40, "sales": 95, "featured": False,
        "desc": "Ultra HD gaming monitor with 144Hz refresh rate, 1ms GtG response time, AMD FreeSync Premium Pro, NVIDIA G-Sync compatibility, and CoreSync ambient lighting.",
        "attr": {"size": "28 inch", "resolution": "4K (3840x2160)", "refresh_rate": "144Hz", "response_time": "1ms", "panel": "IPS HDR400"},
        "images": ["https://images.unsplash.com/photo-1547119957-637f8679db1e?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-APL-STUDIO-DISP",
        "name": "Apple Studio Display 27-inch 5K Retina (Standard Glass, Tilt Stand)",
        "slug": "apple-studio-display-27-5k-retina",
        "category": "laptops-computing",
        "brand": "apple",
        "seller": "techvault",
        "price": 159900.0, "compare": 169900.0, "stock": 10, "rating": 4.8, "reviews": 18, "sales": 45, "featured": False,
        "desc": "Immersive 27-inch 5K Retina display with 600 nits brightness, 12MP Ultra Wide camera with Center Stage, studio-quality three-mic array, and six-speaker sound system.",
        "attr": {"size": "27 inch", "resolution": "5K (5120x2880)", "brightness": "600 nits", "speakers": "6-Speaker High-Fidelity"},
        "images": ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-LOGI-BRIO-4K-CAM",
        "name": "Logitech Brio 4K Ultra HD Pro Webcam with HDR & Noise Reduction",
        "slug": "logitech-brio-4k-webcam",
        "category": "laptops-computing",
        "brand": "logitech",
        "seller": "digitalhub",
        "price": 17995.0, "compare": 21995.0, "stock": 42, "rating": 4.7, "reviews": 75, "sales": 190, "featured": False,
        "desc": "Premier business webcam with 4K UHD streaming at 30fps, RightLight 3 with HDR for challenging lighting, dual omnidirectional microphones, and Windows Hello login.",
        "attr": {"resolution": "4K Ultra HD @ 30fps / 1080p @ 60fps", "field_of_view": "90° / 78° / 65°", "security": "Windows Hello Facial Recognition"},
        "images": ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-APL-MAG-KEYBOARD",
        "name": "Apple Magic Keyboard with Touch ID & Numeric Keypad (Space Black)",
        "slug": "apple-magic-keyboard-touch-id-black",
        "category": "laptops-computing",
        "brand": "apple",
        "seller": "techvault",
        "price": 19500.0, "compare": 21500.0, "stock": 35, "rating": 4.8, "reviews": 38, "sales": 110, "featured": False,
        "desc": "Wireless Bluetooth rechargeable keyboard with built-in Touch ID for fast secure logins and Apple Pay purchases, extended layout with full navigation keys.",
        "attr": {"connectivity": "Bluetooth / Lightning to USB-C", "security": "Touch ID Sensor", "color": "Space Black"},
        "images": ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-LOGI-G502-HERO",
        "name": "Logitech G502 HERO High Performance Gaming Mouse (25K Sensor, RGB)",
        "slug": "logitech-g502-hero-gaming-mouse",
        "category": "laptops-computing",
        "brand": "logitech",
        "seller": "apexcomputex",
        "price": 4295.0, "compare": 5495.0, "stock": 90, "rating": 4.8, "reviews": 320, "sales": 890, "featured": False,
        "desc": "World's best-selling gaming mouse featuring sub-micron HERO 25K optical sensor, 11 programmable buttons, adjustable weight tuning system, and LIGHTSYNC RGB.",
        "attr": {"sensor": "HERO 25K (25,600 DPI)", "buttons": "11 Programmable", "weights": "5x 3.6g Removable Weights"},
        "images": ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-SAN-ULTRA-FLAIR-128",
        "name": "SanDisk Ultra Flair 128GB USB 3.0 Flash Drive (150MB/s Metal Casing)",
        "slug": "sandisk-ultra-flair-128gb-usb-3",
        "category": "laptops-computing",
        "brand": "sandisk",
        "seller": "smartbuystore",
        "price": 899.0, "compare": 1499.0, "stock": 250, "rating": 4.6, "reviews": 410, "sales": 1250, "featured": False,
        "desc": "Sleek durable metallic body with high-speed USB 3.0 file transfers up to 150MB/s, SanDisk SecureAccess 128-bit AES password encryption software.",
        "attr": {"capacity": "128GB", "speed": "150MB/s Read", "interface": "USB 3.0 / USB 2.0 compatible"},
        "images": ["https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-HP-WIRELESS-KEY-MOU",
        "name": "HP Pavilion Wireless Keyboard and Mouse Combo 800 (Black)",
        "slug": "hp-pavilion-wireless-keyboard-mouse-800",
        "category": "laptops-computing",
        "brand": "hp",
        "seller": "smartbuystore",
        "price": 2799.0, "compare": 3999.0, "stock": 115, "rating": 4.4, "reviews": 95, "sales": 420, "featured": False,
        "desc": "Modern low-profile scissor-switch keys with comfortable contoured wireless mouse and single 2.4GHz USB nano-receiver for uncluttered workspace.",
        "attr": {"connectivity": "2.4GHz Wireless Nano Dongle", "battery_life": "Up to 12 months", "color": "Black"},
        "images": ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop"]
    },

    # =========================================================================
    # 2. SMARTPHONES & TABLETS (26 Products)
    # =========================================================================
    {
        "sku": "PHO-APL-IP15P-256-BLK",
        "name": "Apple iPhone 15 Pro (256GB, Black Titanium)",
        "slug": "apple-iphone-15-pro-black-titanium",
        "category": "smartphones-tablets",
        "brand": "apple",
        "seller": "techvault",
        "price": 134900.0, "compare": 144900.0, "stock": 60, "rating": 4.8, "reviews": 115, "sales": 320, "featured": True,
        "desc": "Forged in aerospace-grade titanium with the ground-breaking A17 Pro chip, customizable Action button, and versatile 48MP triple camera system.",
        "attr": {"processor": "A17 Pro", "storage": "256GB", "camera": "48MP Main + 12MP Ultra-Wide + 12MP 3x Telephoto", "display": "6.1 inch Super Retina XDR OLED"},
        "images": ["https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "PHO-SAM-S24U-512-GRY",
        "name": "Samsung Galaxy S24 Ultra 5G (12GB RAM, 512GB, Titanium Gray)",
        "slug": "samsung-galaxy-s24-ultra-titanium-gray",
        "category": "smartphones-tablets",
        "brand": "samsung",
        "seller": "techvault",
        "price": 139999.0, "compare": 149999.0, "stock": 40, "rating": 4.8, "reviews": 98, "sales": 260, "featured": True,
        "desc": "Galaxy AI powered flagship with Snapdragon 8 Gen 3 for Galaxy, integrated S Pen stylus, 200MP quad telephoto camera, and titanium frame.",
        "attr": {"processor": "Snapdragon 8 Gen 3", "ram": "12GB", "storage": "512GB", "camera": "200MP + 50MP + 12MP + 10MP", "battery": "5000mAh 45W"},
        "images": ["https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "PHO-ONEP-12-512-GRN",
        "name": "OnePlus 12 5G (16GB RAM, 512GB Storage, Flowy Emerald)",
        "slug": "oneplus-12-5g-flowy-emerald",
        "category": "smartphones-tablets",
        "brand": "oneplus",
        "seller": "mobilegalaxy",
        "price": 69999.0, "compare": 74999.0, "stock": 45, "rating": 4.8, "reviews": 74, "sales": 215, "featured": True,
        "desc": "Fast & smooth powerhouse with 4th Gen Hasselblad Camera system, 2K 120Hz ProXDR display with Aqua Touch, 5400mAh battery with 100W SUPERVOOC charging.",
        "attr": {"processor": "Snapdragon 8 Gen 3", "ram": "16GB LPDDR5X", "storage": "512GB UFS 4.0", "camera": "50MP Sony LYT-808 + 64MP 3x Periscope", "charging": "100W Wired + 50W Wireless"},
        "images": ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "PHO-XIA-14-512-BLK",
        "name": "Xiaomi 14 5G (12GB RAM, 512GB Storage, Leica Summilux Lens, Black)",
        "slug": "xiaomi-14-5g-leica-black",
        "category": "smartphones-tablets",
        "brand": "xiaomi",
        "seller": "mobilegalaxy",
        "price": 69999.0, "compare": 79999.0, "stock": 35, "rating": 4.7, "reviews": 46, "sales": 140, "featured": False,
        "desc": "Compact flagship co-engineered with Leica. Features Light Fusion 900 sensor with 7P lens, 6.36-inch 1.5K 120Hz LTPO AMOLED display, and 90W HyperCharge.",
        "attr": {"processor": "Snapdragon 8 Gen 3", "ram": "12GB", "storage": "512GB", "camera": "50MP Leica Triple Optics", "display": "6.36 inch 120Hz LTPO"},
        "images": ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "PHO-RLM-12-PRO-PLUS",
        "name": "Realme 12 Pro+ 5G (12GB RAM, 256GB Storage, Submarine Blue)",
        "slug": "realme-12-pro-plus-submarine-blue",
        "category": "smartphones-tablets",
        "brand": "realme",
        "seller": "smartbuystore",
        "price": 29999.0, "compare": 34999.0, "stock": 65, "rating": 4.6, "reviews": 88, "sales": 380, "featured": False,
        "desc": "Luxury watch design inspired by Ollivier Savéo with premium vegan leather back, 64MP periscope portrait telephoto camera, and 120Hz curved AMOLED display.",
        "attr": {"processor": "Snapdragon 7s Gen 2", "camera": "64MP Periscope + 50MP Sony IMX890", "ram": "12GB", "storage": "256GB", "charging": "67W SUPERVOOC"},
        "images": ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "PHO-SAM-A55-5G-ICE",
        "name": "Samsung Galaxy A55 5G (8GB RAM, 256GB, Awesome Iceblue)",
        "slug": "samsung-galaxy-a55-5g-iceblue",
        "category": "smartphones-tablets",
        "brand": "samsung",
        "seller": "primegadgets",
        "price": 39999.0, "compare": 45999.0, "stock": 55, "rating": 4.6, "reviews": 65, "sales": 290, "featured": False,
        "desc": "Refined metal frame with Gorilla Glass Victus+ front & back, 50MP OIS camera with nightography, 120Hz Super AMOLED display, and IP67 water/dust resistance.",
        "attr": {"processor": "Exynos 1480 (4nm)", "ram": "8GB", "storage": "256GB", "display": "6.6 inch Super AMOLED 120Hz", "durability": "IP67 Rating"},
        "images": ["https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "PHO-ONEP-NORD-CE4",
        "name": "OnePlus Nord CE4 5G (8GB RAM, 256GB, Celadon Marble)",
        "slug": "oneplus-nord-ce4-celadon-marble",
        "category": "smartphones-tablets",
        "brand": "oneplus",
        "seller": "smartbuystore",
        "price": 26999.0, "compare": 28999.0, "stock": 80, "rating": 4.7, "reviews": 120, "sales": 510, "featured": False,
        "desc": "Octa-core Snapdragon 7 Gen 3 performance with 100W SUPERVOOC fast charging, 5500mAh high-capacity battery, and Sony LYT-600 OIS camera.",
        "attr": {"processor": "Snapdragon 7 Gen 3", "ram": "8GB", "storage": "256GB", "battery": "5500mAh 100W", "display": "6.7 inch 120Hz AMOLED"},
        "images": ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "PHO-XIA-REDMI-13-PRO-PLUS",
        "name": "Redmi Note 13 Pro+ 5G (12GB RAM, 256GB, Fusion Purple)",
        "slug": "redmi-note-13-pro-plus-purple",
        "category": "smartphones-tablets",
        "brand": "xiaomi",
        "seller": "smartbuystore",
        "price": 31999.0, "compare": 37999.0, "stock": 70, "rating": 4.6, "reviews": 90, "sales": 440, "featured": False,
        "desc": "Flagship 200MP Samsung ISOCELL HP3 camera with OIS, 1.5K 3D curved 120Hz AMOLED display, IP68 water resistance, and 120W HyperCharge.",
        "attr": {"camera": "200MP OIS Triple Camera", "charging": "120W HyperCharge", "processor": "MediaTek Dimensity 7200-Ultra", "durability": "IP68"},
        "images": ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "TAB-APL-IPAD-AIR-M2",
        "name": "Apple iPad Air 11-inch M2 Chip (128GB Wi-Fi, Space Grey)",
        "slug": "apple-ipad-air-11-m2-space-grey",
        "category": "smartphones-tablets",
        "brand": "apple",
        "seller": "techvault",
        "price": 59900.0, "compare": 64900.0, "stock": 40, "rating": 4.9, "reviews": 65, "sales": 230, "featured": True,
        "desc": "Supercharged by Apple M2 with 8-core CPU and 10-core GPU. Liquid Retina display with P3 wide color, landscape 12MP front camera with Center Stage, Apple Pencil Pro support.",
        "attr": {"processor": "Apple M2", "storage": "128GB", "display": "11 inch Liquid Retina", "accessories": "Apple Pencil Pro compatible"},
        "images": ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "TAB-SAM-TAB-S9-FE",
        "name": "Samsung Galaxy Tab S9 FE 10.9-inch (6GB RAM, 128GB, S-Pen, Gray)",
        "slug": "samsung-galaxy-tab-s9-fe-gray",
        "category": "smartphones-tablets",
        "brand": "samsung",
        "seller": "primegadgets",
        "price": 36999.0, "compare": 44999.0, "stock": 45, "rating": 4.7, "reviews": 52, "sales": 180, "featured": False,
        "desc": "IP68 water-resistant tablet with included S Pen for sketch and notes, 90Hz vivid screen with Vision Booster, AKG dual speakers, and 8000mAh battery.",
        "attr": {"display": "10.9 inch 90Hz WQXGA", "ram": "6GB", "storage": "128GB", "pen": "S Pen in Box", "durability": "IP68"},
        "images": ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "TAB-APL-IPAD-10-64",
        "name": "Apple iPad 10th Gen 10.9-inch (64GB Wi-Fi, Blue)",
        "slug": "apple-ipad-10th-gen-blue",
        "category": "smartphones-tablets",
        "brand": "apple",
        "seller": "techvault",
        "price": 34900.0, "compare": 39900.0, "stock": 55, "rating": 4.8, "reviews": 140, "sales": 490, "featured": False,
        "desc": "All-screen design with 10.9-inch Liquid Retina display, A14 Bionic chip, landscape 12MP Ultra Wide camera, USB-C connectivity, and Touch ID power button.",
        "attr": {"processor": "A14 Bionic", "storage": "64GB", "display": "10.9 inch Liquid Retina", "connector": "USB-C"},
        "images": ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "TAB-XIA-PAD-6-256",
        "name": "Xiaomi Pad 6 11-inch (8GB RAM, 256GB Storage, Snapdragon 870, Mist Blue)",
        "slug": "xiaomi-pad-6-mist-blue-256gb",
        "category": "smartphones-tablets",
        "brand": "xiaomi",
        "seller": "smartbuystore",
        "price": 28999.0, "compare": 32999.0, "stock": 50, "rating": 4.7, "reviews": 78, "sales": 310, "featured": False,
        "desc": "Unibody metal build with 144Hz 2.8K display with Dolby Vision, Snapdragon 870 processor, quad speakers with Dolby Atmos, and 8840mAh battery with 33W fast charge.",
        "attr": {"display": "11 inch 2.8K 144Hz", "processor": "Snapdragon 870", "ram": "8GB", "storage": "256GB", "audio": "Quad Speakers Dolby Atmos"},
        "images": ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "TAB-ONEP-PAD-GO-128",
        "name": "OnePlus Pad Go 11.35-inch 2.4K Eye-Care Display (8GB RAM, 128GB LTE)",
        "slug": "oneplus-pad-go-twin-mint-lte",
        "category": "smartphones-tablets",
        "brand": "oneplus",
        "seller": "mobilegalaxy",
        "price": 21999.0, "compare": 23999.0, "stock": 60, "rating": 4.6, "reviews": 55, "sales": 240, "featured": False,
        "desc": "Two-tone Twin Mint finish with TÜV Rheinland certified low blue light 2.4K display, 4G LTE SIM support, quad speakers with Omnibearing Sound Field, and 8000mAh battery.",
        "attr": {"display": "11.35 inch 2.4K (2408x1720)", "connectivity": "4G LTE + Wi-Fi", "ram": "8GB", "storage": "128GB"},
        "images": ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-APL-20W-ADAPTER",
        "name": "Apple 20W USB-C Power Adapter (Original Fast Charging)",
        "slug": "apple-20w-usb-c-power-adapter",
        "category": "smartphones-tablets",
        "brand": "apple",
        "seller": "techvault",
        "price": 1899.0, "compare": 1900.0, "stock": 180, "rating": 4.8, "reviews": 310, "sales": 1100, "featured": False,
        "desc": "Fast, efficient charging at home, in the office, or on the go. Compatible with any USB-C enabled device, optimized for iPhone 15, iPad, and AirPods.",
        "attr": {"output": "20W", "connector": "USB-C", "compatibility": "iPhone, iPad, AirPods"},
        "images": ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-SAM-45W-CHARGER",
        "name": "Samsung 45W USB-C Super Fast Charging Adapter with C-to-C Cable",
        "slug": "samsung-45w-super-fast-charging-adapter",
        "category": "smartphones-tablets",
        "brand": "samsung",
        "seller": "primegadgets",
        "price": 2999.0, "compare": 3999.0, "stock": 95, "rating": 4.8, "reviews": 160, "sales": 580, "featured": False,
        "desc": "Power Delivery (PD) 3.0 PPS super fast charger capable of fueling Galaxy S24 Ultra from 0 to 65% in approximately 30 minutes.",
        "attr": {"output": "45W Super Fast Charging 2.0", "standard": "USB PD 3.0 PPS", "cable": "5A 1.8m C-to-C Included"},
        "images": ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-MI-20000-PW-BANK",
        "name": "Mi 20000mAh 50W HyperCharge Power Bank (Triple Output, Type-C)",
        "slug": "mi-20000mah-50w-hypercharge-power-bank",
        "category": "smartphones-tablets",
        "brand": "xiaomi",
        "seller": "smartbuystore",
        "price": 3499.0, "compare": 4499.0, "stock": 130, "rating": 4.7, "reviews": 240, "sales": 820, "featured": False,
        "desc": "Charges phones and laptops alike with 50W MAX Type-C output, 20,000mAh airline-approved lithium-ion polymer battery, and two-way fast charging.",
        "attr": {"capacity": "20,000mAh", "max_output": "50W Fast Charge", "ports": "1x USB-C + 2x USB-A"},
        "images": ["https://images.unsplash.com/photo-1609592426508-cc02728d8b67?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-BOAT-ENERGIE-10K",
        "name": "boAt Energie 10000mAh 22.5W Fast Charging Power Bank (Carbon Black)",
        "slug": "boat-energie-10000mah-power-bank",
        "category": "smartphones-tablets",
        "brand": "boat",
        "seller": "smartbuystore",
        "price": 1299.0, "compare": 2499.0, "stock": 175, "rating": 4.5, "reviews": 185, "sales": 740, "featured": False,
        "desc": "Compact pocket power bank with Quick Charge 3.0 & Power Delivery 22.5W output, Smart IC protection against overheating, and premium aluminum shell.",
        "attr": {"capacity": "10,000mAh", "speed": "22.5W Fast Charge", "body": "Aluminum Casing"},
        "images": ["https://images.unsplash.com/photo-1609592426508-cc02728d8b67?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-SPIGEN-IP15P-CASE",
        "name": "Spigen Rugged Armor Case for iPhone 15 Pro (Matte Black)",
        "slug": "spigen-rugged-armor-iphone-15-pro-case",
        "category": "smartphones-tablets",
        "brand": "apple",
        "seller": "mobilegalaxy",
        "price": 1499.0, "compare": 2199.0, "stock": 140, "rating": 4.8, "reviews": 190, "sales": 680, "featured": False,
        "desc": "Mil-grade certified drop protection with Air Cushion Technology, carbon fiber detailing, flexible TPU shock absorption, and tactile button cutouts.",
        "attr": {"compatibility": "iPhone 15 Pro", "material": "Flexible TPU with Carbon Accents", "protection": "Mil-Grade Drop Tested"},
        "images": ["https://images.unsplash.com/photo-1541877590-a09560960b5b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-SPIGEN-S24U-CASE",
        "name": "Spigen Liquid Air Armor Back Cover for Samsung Galaxy S24 Ultra",
        "slug": "spigen-liquid-air-samsung-s24-ultra-case",
        "category": "smartphones-tablets",
        "brand": "samsung",
        "seller": "mobilegalaxy",
        "price": 1399.0, "compare": 1999.0, "stock": 120, "rating": 4.7, "reviews": 135, "sales": 490, "featured": False,
        "desc": "Geometric modern triangle texture with anti-slip matte grip, slim pocket-friendly silhouette, and raised bezels around the 200MP camera lenses.",
        "attr": {"compatibility": "Galaxy S24 Ultra", "finish": "Matte Geometric Pattern", "grip": "Anti-Slip Grip"},
        "images": ["https://images.unsplash.com/photo-1541877590-a09560960b5b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-ONEP-100W-DUAL",
        "name": "OnePlus SUPERVOOC 100W Dual Ports Power Adapter (Type-A + Type-C)",
        "slug": "oneplus-supervooc-100w-dual-port-adapter",
        "category": "smartphones-tablets",
        "brand": "oneplus",
        "seller": "primegadgets",
        "price": 3999.0, "compare": 4999.0, "stock": 65, "rating": 4.9, "reviews": 85, "sales": 310, "featured": False,
        "desc": "Next-gen GaN dual-port fast charger delivering full 100W output for OnePlus smartphones, tablets, and compatible Power Delivery laptops.",
        "attr": {"wattage": "100W GaN", "ports": "Dual Ports (Type-A + Type-C)", "compatibility": "SUPERVOOC, PD, QC"},
        "images": ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-APL-MAGSAFE-CHG",
        "name": "Apple MagSafe Wireless Charger (15W Fast Magnetic Induction)",
        "slug": "apple-magsafe-wireless-charger",
        "category": "smartphones-tablets",
        "brand": "apple",
        "seller": "techvault",
        "price": 4500.0, "compare": 4500.0, "stock": 85, "rating": 4.7, "reviews": 110, "sales": 410, "featured": False,
        "desc": "Perfect magnetic alignment every time. Snaps into place on iPhone 12 through 15 models for faster wireless charging up to 15W.",
        "attr": {"charging_speed": "Up to 15W", "standard": "Qi Magnetic Induction", "cable_length": "1 meter integrated USB-C"},
        "images": ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-ESR-IP15P-SCREEN",
        "name": "ESR Armorite 9H Tempered Glass Screen Protector for iPhone 15 Pro (2-Pack)",
        "slug": "esr-armorite-tempered-glass-iphone-15-pro",
        "category": "smartphones-tablets",
        "brand": "apple",
        "seller": "mobilegalaxy",
        "price": 999.0, "compare": 1499.0, "stock": 190, "rating": 4.8, "reviews": 230, "sales": 870, "featured": False,
        "desc": "Ultra-tough 9H tempered glass capable of withstanding up to 110 lbs of impact force, with easy auto-alignment installation frame and oleophobic coating.",
        "attr": {"hardness": "9H Armorite", "pack": "2 Screen Protectors", "coating": "Anti-fingerprint Oleophobic"},
        "images": ["https://images.unsplash.com/photo-1541877590-a09560960b5b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-BOAT-RUGGED-CABLE",
        "name": "boAt Deuce USB 300 2-in-1 Type-C & Micro USB Cable (1.5m Braided)",
        "slug": "boat-deuce-usb-300-braided-cable",
        "category": "smartphones-tablets",
        "brand": "boat",
        "seller": "smartbuystore",
        "price": 349.0, "compare": 799.0, "stock": 300, "rating": 4.5, "reviews": 450, "sales": 1800, "featured": False,
        "desc": "Indestructible nylon braided sync & charge cable with 3A fast charging, aluminum alloy connectors, and 10,000+ bend lifespan test certification.",
        "attr": {"length": "1.5 meters", "speed": "3A Fast Charging (480Mbps data)", "material": "High-Grade Nylon Braided"},
        "images": ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-REALME-BUDS-CASE",
        "name": "Realme Magnetic Silicone Protective Case for Wireless Earbuds",
        "slug": "realme-silicone-protective-case-earbuds",
        "category": "smartphones-tablets",
        "brand": "realme",
        "seller": "smartbuystore",
        "price": 499.0, "compare": 999.0, "stock": 160, "rating": 4.4, "reviews": 85, "sales": 320, "featured": False,
        "desc": "Soft touch food-grade silicone skin with 360-degree shock absorption, dust cap for USB-C port, and aluminum carabiner clip for backpack attachment.",
        "attr": {"material": "Liquid Silicone", "features": "Carabiner included, Wireless charging compatible"},
        "images": ["https://images.unsplash.com/photo-1541877590-a09560960b5b?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-SAM-TRIO-PAD-CHG",
        "name": "Samsung Wireless Charger Trio (Charges Phone, Watch, and Buds Simultaneously)",
        "slug": "samsung-wireless-charger-trio-black",
        "category": "smartphones-tablets",
        "brand": "samsung",
        "seller": "primegadgets",
        "price": 7999.0, "compare": 9999.0, "stock": 40, "rating": 4.7, "reviews": 60, "sales": 170, "featured": False,
        "desc": "All-in-one charging station equipped with six coils for versatile placement. Powers your Galaxy smartphone, Galaxy Watch, and Galaxy Buds at once.",
        "attr": {"charging_spots": "3 Devices Simultaneously", "speed": "9W Fast Wireless", "color": "Black"},
        "images": ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop"]
    },
    {
        "sku": "ACC-PHO-DESK-STAND-ALU",
        "name": "Apex Pro Adjustable Aluminum Desktop Phone & Tablet Stand (Foldable)",
        "slug": "apex-pro-aluminum-phone-tablet-stand",
        "category": "smartphones-tablets",
        "brand": "logitech",
        "seller": "smartbuystore",
        "price": 799.0, "compare": 1499.0, "stock": 210, "rating": 4.7, "reviews": 310, "sales": 950, "featured": False,
        "desc": "CNC machined solid aerospace aluminum stand with dual 270-degree rotational hinges, anti-slip silicone cushions, and reserved charging cable cutout.",
        "attr": {"compatibility": "Phones and Tablets 4 to 12.9 inch", "material": "Solid Aluminum Alloy", "portability": "Fully Foldable"},
        "images": ["https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&auto=format&fit=crop"]
    }
]
